### ISSUE TITLE
static const with in-class initializer should be converted to a constant rather than extern static

### ISSUE THREAD

**Issue by upsuper** [servo/rust-bindgen#101]
Currently, static consts in class are all converted to `extern "C" pub static`, however, when the static const has in-class initializer, we should be able to convert it to a constant like macro.

FWIW, C++ only allows static const which has integer type or enum type to have in-class initializer.

**Comment by upsuper** [comment]
I think this makes #84 less urgent.

**Comment by emilio** [comment]
Currently the following code doesn't generate any `extern "C" pub static`:

```c++
class Foo {
  static const int I = 0;
};
```

And generates the proper constant. Probably with enums doesn't work though, if that's the case you're asking for. Do you have a test-case I can look when I arrive from class? Thanks! :)

**Comment by upsuper** [comment]
Oh, interesting. This code does generate `extern "C" pub static`:
```c++
typedef unsigned int uint32_t;

struct A {
  static const uint32_t kA = 0;
};
```
