### ISSUE TITLE
alignment of integer field holding bitfield values is not correct

### ISSUE THREAD

**Issue by heycam** [servo/rust-bindgen#111]
The use of a single integer-typed field to represent contiguous bitfield members results in layout that doesn't match the layout generated by the corresponding C++ struct.  For example with:

``` C++
struct A
{
  uint8_t x;
  unsigned b1 : 1;
  unsigned b2 : 1;
  unsigned b3 : 1;
  unsigned b4 : 1;
  unsigned b5 : 1;
  unsigned b6 : 1;
  unsigned b7 : 1;
  unsigned b8 : 1;
  unsigned b9 : 1;
  unsigned b10 : 1;
  uint8_t y;
};
...
printf("offsetof(A, y) = %d\n", (int) offsetof(A, y));
```

I get an output of `3` when compiled with clang, but rust-bindgen generates:

``` rust
#[repr(C)]
#[derive(Debug, Copy)]
pub struct A {
    pub x: u8,
    pub _bitfield_1: u16,
    pub y: u8,
}
```

which places `y` at offset 4.

Packing and alignment of bitfields is probably implementation dependent, but we should generate the same layout that clang does.  It might just be a matter of generating a sequence of `u8`s to hold the contiguous bitfields.

cc @emilio

**Comment by emilio** [comment]
Thanks for filling this, I have it in the radar, though I doubt it's so as easy as generating `u8`s, specially taking alignment into account.

For example, `unsigned int foo: 32` provokes the container struct to be 4-byte aligned.

Probably the easiest way to do this properly is to look at llvm's source.

**Comment by emilio** [comment]
I'm looking into this right now since bindgenup in stylo is blocked on this now we check for field offsets.
