### ISSUE TITLE
clang::Cursor::semantic_parent should call clang::Cursor::fallible_semantic_parent -- not the other way around

### ISSUE THREAD

**Issue by fitzgen** [servo/rust-bindgen#120]
Right now, `clang::Cursor::fallible_semantic_parent` calls `clang::Cursor::semantic_parent` and does some validation and error checking, and it is `clang::Cursor::semantic_parent` that does the ffi call to `clang_getCursorSemanticParent`. This means that `clang::Cursor::semantic_parent` isn't very safe, since the result was never validated. We should make `fallible_semantic_parent` do the ffi call _and_ validation, and then have `semantic_parent` call `fallible_semantic_parent().unwrap()` so that we are properly verifying return values regardless what method we call.

I can mentor someone who would like to pick up this bug.

**Comment by malisas** [comment]
I'll work on this :)

**Comment by fitzgen** [comment]
Great! Let me know if you have run into any trouble building or running tests or anything like that!
