### ISSUE TITLE
clang::Cursor::num_template_args should return Option<u32>

### ISSUE THREAD

**Issue by fitzgen** [servo/rust-bindgen#121]
Right now it returns a `c_int`, but the documentation for `clang_Cursor_getNumTemplateArgs` says it returns `-1` if the cursor's referent is not a template declaration or specialization. We should translate negative values into `None` and positive values into `Some`. This will also require fixing up callers.

I can mentor someone who wants to pick up this bug.

**Comment by Incognitas** [comment]
Should it return Option<u32> instead of Option<usize> (as c_int == i32, this is the closest unsigned type) ? 
Furthermore, This would be more consistent with other API definitions like Type::num_template_args() returning already Option<u32>.

**Comment by emilio** [comment]
Yeah, both `u32` and `usize` are fine. `Type::num_template_args` is gone now, but I agree.

**Comment by Incognitas** [comment]
Ok, I will take care of this issue then.

**Comment by emilio** [comment]
Great, thanks!
