### ISSUE TITLE
clang::Cursor::specialized should return an Option<clang::Cursor>

### ISSUE THREAD

**Issue by fitzgen** [servo/rust-bindgen#122]
Right now, `clang::Cursor::specialized` returns a `clang::Cursor` regardless if that resulting cursor `is_valid()` or not. This is a footgun for callers, which have to remember to check `resulting_cursor.is_valid()`. Instead, `specialized` should check for them and return `None` if it is not a valid cursor, and `Some` if it is.

I can mentor someone who would like to pick up this bug.

**Comment by glasserc** [comment]
This looks fun and I will give it a shot today!

**Comment by fitzgen** [comment]
Great! Don't hesitate to reach out if you run into any roadblocks :)

**Comment by glasserc** [comment]
This might be a silly question, but why is it possible for a cursor to be invalid? Shouldn't the presence of a `Cursor` mean that it is valid and that you can use it? Shouldn't invalid cursors themselves be represented using `None` or something? I guess that's a larger issue than just changing this one method though..

**Comment by fitzgen** [comment]
Agreed! But we're using FFI to Clang and we don't get to decide how Clang represents its data structures :)

We *do* want to make it so that our wrapper `Cursor` type never contains a null or invalid Clang cursor, but this is a bit more work (or at least requires some more investigation and experimentation). See #119.

Fixing issues like this one will certainly help us get there, though!
