### ISSUE TITLE
clang::Cursor::referenced should return Option<clang::Cursor>

### ISSUE THREAD

**Issue by fitzgen** [servo/rust-bindgen#124]
It does not check if the resulting cursor `is_valid()`, requiring callers to do it, which is a foot gun. Instead, it should check `resulting_cursor.is_valid()` and return either `None` or `Some`. We will also need to fix callers.

I can mentor anyone who wants to pick up this bug.

**Comment by codingHahn** [comment]
@fitzgen How difficult is this bug? I am just getting my foot wet with rust. I am aprox. halfway trough the Rust book (the main one  on the website).

**Comment by emilio** [comment]
@codingHahn This should be doable with that experience :)
