### ISSUE TITLE
clang::Cursor::enum_type should return an Option<Type>

### ISSUE THREAD

**Issue by fitzgen** [servo/rust-bindgen#125]
It does not check if the resulting type's kind is `CXType_Invalid`, requiring callers to do it, which is a foot gun. Instead, it should check for the invalid case itself and return either `None` or `Some` depending. We will also need to fix callers.

I can mentor anyone who wants to pick up this bug.

**Comment by tsliang** [comment]
I would like to help out with this one. I don't expect I'll have problems (I've been playing with Rust quite a bit lately), but @fitzgen if I need some guidance is it better to reach out to you via Github or hop on IRC?

**Comment by fitzgen** [comment]
Great!

If it is during the workday (PST), then irc is great, otherwise leaving a comment here is probably best.
