### ISSUE TITLE
clang::Cursor::enum_value_signed should return Option<i64>

### ISSUE THREAD

**Issue by fitzgen** [servo/rust-bindgen#127]
Right now it _always_ returns i64, but the FFI call it makes says

http://clang.llvm.org/doxygen/group__CINDEX__TYPES.html#ga6b8585818420e7512feb4c9d209b4f4d

> Retrieve the integer value of an enum constant declaration as a signed long long.
> 
> If the cursor does not reference an enum constant declaration, LLONG_MIN is returned. Since this is also potentially a valid constant value, the kind of the cursor must be verified before calling this function.

We shouldn't force callers to check the kind of the cursor, we should do the check ourselves in this function and return an option. This would result in one less foot gun.

I can mentor anyone who'd like to pick up this bug.

**Comment by jcdyer** [comment]
I'll take on this one.

**Comment by jcdyer** [comment]
I'm assuming `enum_value_signed` is the same thing as `enum_val_signed`.

**Comment by jcdyer** [comment]
I took a stab at reorganizing the caller to make more fluent use of the Option, which should make things more straightforward when #128 lands.
