### ISSUE TITLE
clang::Cursor::enum_val_unsigned should return Option<u64>

### ISSUE THREAD

**Issue by fitzgen** [servo/rust-bindgen#128]
(Similar to #127)

Right now it _always_ returns u64, but the FFI call it makes says

http://clang.llvm.org/doxygen/group__CINDEX__TYPES.html#gaf7cbd4f2d371dd93e8bc997c951a1aef

> Retrieve the integer value of an enum constant declaration as an unsigned long long.
> 
> If the cursor does not reference an enum constant declaration, ULLONG_MAX is returned. Since this is also potentially a valid constant value, the kind of the cursor must be verified before calling this function.

We shouldn't force callers to check the kind of the cursor, we should do the check ourselves in this function and return an option. This would result in one less foot gun.

I can mentor anyone who'd like to pick up this bug.

**Comment by afluth** [comment]
I would like to take a swing at this.

**Comment by emilio** [comment]
Sure, thanks for it! :)

**Comment by jcdyer** [comment]
@afluth, I've got PR #127 coming in that (if accepted) reorganizes the calling code in enum_ty.rs a little bit.

**Comment by afluth** [comment]
@jcdyer, thanks for the heads up!
