### ISSUE TITLE
clang::Cursor::typedef_type should return Option<Type>

### ISSUE THREAD

**Issue by fitzgen** [servo/rust-bindgen#129]
The [FFI call](http://clang.llvm.org/doxygen/group__CINDEX__TYPES.html#ga8de899fc18dc859b6fe3b97309f4fd52) that `typedef_type` makes will return an invalid type if the cursor's referent is not a typedef. We should check whether the referent is a typedef and return `None` if it is not, and make the FFI call and return `Some` if it is a typedef. This would be one less foot gun.

I can mentor anyone who'd like to pick up this bug.

**Comment by codingHahn** [comment]
How difficult is this? I am just getting my foots wet with rust. I am almost halfway through the Rust book form the website.

**Comment by codingHahn** [comment]
Ok. I should implement the check inside the function and return ```Some()``` or ```None```? And every calling that checks the validity of this function should be wrapped into ```is_some()``` etc.? And every other function calling should have ```.expect(sth)```? Then a am working on it in the next couple days.

**Comment by fitzgen** [comment]
Yep that sounds right! Let me know if you run into any roadblocks.

**Comment by codingHahn** [comment]
I'll let you know :)

**Comment by impowski** [comment]
@codingHahn Have you done any progress on that or I can take it?
