### ISSUE TITLE
clang::Cursor::ret_type should return an Option<Cursor>

### ISSUE THREAD

**Issue by fitzgen** [servo/rust-bindgen#131]
Right now it always returns a `Cursor` but it makes an FFI call to `clang_Cursor_getCursorResultType` which is only valid if the cursor's referent is a function or method declarations and calls:

http://clang.llvm.org/doxygen/group__CINDEX__TYPES.html#ga6995a2d6352e7136868574b299005a63

> This only returns a valid type if the cursor refers to a function or method. 

We should check whether the cursor referent is a valid function/method call/decl kind, and if it is not, we should return `None`. This will be one less foot gun.

I can mentor whoever would like to pick up this bug.

**Comment by Natim** [comment]
I am going to give it a try.

**Comment by Natim** [comment]
> clang::Cursor::ret_type should return an Option<Cursor>

I think it should return an `Option<Type>` instead of a `Type` correct?

**Comment by Wafflespeanut** [comment]
Precisely!

**Comment by Natim** [comment]
Well I am kind of puzzled that the tests still pass 😞
