### ISSUE TITLE
clang::Cursor::num_args should return Option<u32>

### ISSUE THREAD

**Issue by fitzgen** [servo/rust-bindgen#132]
Right now we just directly do an FFI call that returns -1 if the cursor's referent is not a function/method call or declaration. We should inspect the return value and return `None` if it is `-1` or `Some` if it is `>= 0`. This would be one less foot gun where we require callers of this method to remember to check.

http://clang.llvm.org/doxygen/group__CINDEX__TYPES.html#ga5254f761b57fd78de3ac9c6bfcaa7fed
> For other cursors -1 is returned. 

I can mentor whoever picks up this bug.

**Comment by malfunc** [comment]
added PR https://github.com/servo/rust-bindgen/pull/150
