### ISSUE TITLE
clang::Cursor::template_arg_value should behave defensively

### ISSUE THREAD

**Issue by fitzgen** [servo/rust-bindgen#134]
We should check that the cursor's referent is a template specialization and that `i` is not out of bounds. If either of those things don't hold, we should return `None` and avoid the FFI call. There is no way to check the return value for validity if we mess this up: the behavior is undefined! Otherwise, we should make the FFI call and return `Some`.

This would be a nice removal of a foot gun.

http://clang.llvm.org/doxygen/group__CINDEX__TYPES.html#ga46e363545effaa0794a2ba4bcfae1fe3

> It is undefined to call this function on a CXCursor that does not represent a FunctionDecl or whose I'th template argument is not an integral value.

I can mentor whoever would like to work on this bug.

**Comment by cynicaldevil** [comment]
I'll take a shot at this one!

**Comment by fitzgen** [comment]
Great! Let me know if you run into any road blocks :)
