### ISSUE TITLE
clang::Type::elem_type should return Option<Type>

### ISSUE THREAD

**Issue by fitzgen** [servo/rust-bindgen#138]
We make this FFI call:

http://clang.llvm.org/doxygen/group__CINDEX__TYPES.html#gab35027c8bc48fab25f7698a415c93922

> If a type is passed in that is not an array, complex, or vector type, an invalid type is returned. 

We should check for an invalid type result and return `None`, otherwise `Some`.

This change means that every caller won't have to do this check themselves, which is one less foot gun.

i can mentor whoever works on this bug.

**Comment by Incognitas** [comment]
I can work on this one.

**Comment by fitzgen** [comment]
Great! Let me know if you have any questions or run into any road blocks :)
