### ISSUE TITLE
clang::Type::num_elements should return Option<usize>

### ISSUE THREAD

**Issue by fitzgen** [servo/rust-bindgen#139]
We make an FFI call to `clang_getNumElements` but don't check the return value. We should check for failure and return `None` if we find it, only casting to usize and returning `Some` after we've verified a successful result.

http://clang.llvm.org/doxygen/group__CINDEX__TYPES.html#gac5f636020c388126bec572cb1fb13007
> If a type is passed in that is not an array or vector type, -1 is returned. 

This will be one less foot gun for callers that currently need to remember to check (for `std::usize::MAX == -1 as usize`? I doubt any do...).

I can mentor whoever wants to work on this.

**Comment by catdesk** [comment]
I'm working on it!
