### ISSUE TITLE
clang::Type::arg_types should return Option<Vec<Type>>

### ISSUE THREAD

**Issue by fitzgen** [servo/rust-bindgen#140]
`arg_types` makes FFI calls that are only valid if this type is a function type. We should check whether or not this type is a function type, and if it is not, then return `None`. If it is, we should proceed with the FFI calls and return `Some`.

This will make it so that every caller doesn't have to remember to do the check, which removes a foot gun if they forget.

I can mentor whoever would like to work on this bug.

**Comment by rloisel** [comment]
Hi, can I work on this ?

**Comment by fitzgen** [comment]
Yep! Let me know if you run into any roadblocks or have questions or anything :)

**Comment by rloisel** [comment]
Sure :).
Actually I have 2 questions : 
- To detect if the cursor is a function I think about using `clang_isFunctionInlined`, any advice on that one ?
- I would like to add a unit test for this but I don't really understand the test structure in this project. Where could I add a test for `arg_types` method ?

Cheers

**Comment by fitzgen** [comment]
It might actually be easier to always make the FFI call and then check the result for validity.

http://clang.llvm.org/doxygen/group__CINDEX__TYPES.html#ga705e1a4ed7c7595606fc30ed5d2a6b5a
> If a non-function type is passed in, -1 is returned. 

You can use check if the returned value for the number of args and if it is `-1`, then return `None`, otherwise proceed getting each argument type.

As for unit tests, unfortunately this particular code isn't setup great for unit tests, and adding new ones won't be straight forward. I suggest just ensuring that the existing integration test suite is passing (see `CONTRIBUTING.md` for details).

Hope that helps!

**Comment by rloisel** [comment]
Thanks for your help !

I updated the code to do so, everything seems alright at compilation, unit tests are passing.
But as I cant add unit test I dont know how to test that piece of code. :s

**Comment by fitzgen** [comment]
Great! \o/

> But as I cant add unit test I dont know how to test that piece of code. :s

In this case, I think it is fine to go ahead and open a pull request without any unit tests specific to this issue.
