### ISSUE TITLE
clang::Type::ret_type should return Option<Type>

### ISSUE THREAD

**Issue by fitzgen** [servo/rust-bindgen#141]
`ret_type` does an FFI call to `clang_getReturnType`, which returns an invalid type if the input type is not a function type. We should check for the invalid type result, and return `None`, and otherwise return `Some`.

This will save callers from needing to remember to do this check, which is one less foot gun if they forget.

I can mentor whoever would like to work on this.

**Comment by jeanphilippeD** [comment]
Hello,
I'd like to try an address this issue. I should have a PR ready soon.
I assumed you meant 'clang_getResultType'.

I'm not completely sure about the kind of error handling we want for one of the caller, but other similar PR have used expect, so I'll default to that for now.
Thanks,
JP
