### ISSUE TITLE
clang::Comment::num_children should bounds check its argument

### ISSUE THREAD

**Issue by fitzgen** [servo/rust-bindgen#142]
The Clang docs don't specify what happens if we request a child comment that is out of bounds. We should make sure we don't do it at all. We can make the function return an `Option<Comment>` instead of plain `Comment` and return `None` if `i >= self.num_children()`. Otherwise we can proceed normally and return `Some`.

I can mentor whoever would like to work on this.

**Comment by catdesk** [comment]
I'd like to work on this, but is it actually Comment::get_child that needs to be modified?
