### ISSUE TITLE
clang::Diagnostic::dispose should be a Drop impl for clang::Diagnostic

### ISSUE THREAD

**Issue by fitzgen** [servo/rust-bindgen#145]
`dispose` destroys the diagnostic message and it is unsafe to use after having called `dispose`. It should be a `Drop` implementation instead of a method that even makes it possible to continue to use after it has been destroyed.

I don't know how much we depend on this messed up behavior, so this involves some trial and error and investigation into our uses of `Diagnostic`. It would be a good second or third bug, so marking this `E-less-easy` rather than `E-easy`.

**Comment by fitzgen** [comment]
Also, we don't ever even call `dispose` right now >.<

**Comment by KiChjang** [comment]
Investigating this.
