### ISSUE TITLE
s/type_resolver/ctx/ in src/ir/comp.rs

### ISSUE THREAD

**Issue by fitzgen** [servo/rust-bindgen#147]
There used to a `TypeResolver` thing -- now there is just `BindgenContext`. We should rename all the `type_resolver` variables to `ctx`, which is the usual name for `BindgenContext`.

This is a good first bug, and I can mentor whoever would like to take this on.

**Comment by malfunc** [comment]
I can do it.

**Comment by fitzgen** [comment]
Great! Feel free to ping me on irc or comment here if you run into any trouble building, running tests, or anything!

**Comment by fitzgen** [comment]
Fixed in #148 -- Thanks @malfunc!
