### ISSUE TITLE
Log libclang version information.

### ISSUE THREAD

**Issue by emilio** [servo/rust-bindgen#152]
Seems straight-forward with `clang_getClangVersion`.

**Comment by fitzgen** [comment]
And maybe also:

```rust
if cfg!(feature = "llvm_stable") {
    assert_eq!(version, 3.8);
} else {
    assert_eq!(version, 3.9);
}
```

**Comment by emilio** [comment]
Yeah, or at least a warning, given that C code is likely to work with any of them.

Apparently `clang_getClangVersion` isn't intended to be parsed, so I'd prefer us not trying, but it seems really helpful for debugging issues.

**Comment by oldmanmike** [comment]
I'd like to handle this one.

**Comment by emilio** [comment]
That'd be great!

Let us know if you need any help with it, thanks! :)

**Comment by Natim** [comment]
If it was merged maybe we can close this issue :)

**Comment by emilio** [comment]
Yup!
