### ISSUE TITLE
(Re?) enable CI testing on OSX

### ISSUE THREAD

**Issue by fitzgen** [servo/rust-bindgen#154]
Looking at `.travis.yml`, I think that we used to test on OSX, but we certainly aren't anymore. Presumably because we don't have LLVM 3.9 on Travis CI yet?

We should start testing on OSX again when we can figure that out. This issue can track that work.

**Comment by emilio** [comment]
I don't remember when/if we tested on OSX, but I'm pretty sure getting llvm38 from brew is doable, and probably llvm39 too.

If we could test llvm39 on OSX that'd be great until #70 lands!

**Comment by KyleMayes** [comment]
I have working CI for macOS (and Windows) on my clang-related projects, I'm working on a pull request for this.

**Comment by fitzgen** [comment]
Great! Thanks a bunch :)

**Comment by emilio** [comment]
This is done \o/ thanks @KyleMayes
