### ISSUE TITLE
Use iterators for comment children, attributes, etc.

### ISSUE THREAD

**Issue by emilio** [servo/rust-bindgen#166]
It's easier, more efficient, and more readable than all the bound-checking we're doing, specially taking into account that each bound check is an extra ffi call.

**Comment by emilio** [comment]
cc @fitzgen

**Comment by jeanphilippeD** [comment]
Hello,
I'd quite like to try to do this, for comment children first, since it seems simpler.
Would it be ok?

Would it be reasonable to follow the accepted answer here as a guide?
http://stackoverflow.com/questions/30218886/how-to-implement-iterator-and-intoiterator-for-a-simple-struct

**Comment by emilio** [comment]
Sure, it'd be great!

Yeah, that answer seems pretty reasonable :)

**Comment by jeanphilippeD** [comment]
Does this issue make #143 redundant?

**Comment by emilio** [comment]
> Does this issue make #143 redundant?

Agh, sort of, I didn't read this comment soon enough.

That being said, another contributor had already made progress in that issue, so I think that should be merged. If you could rebase your patch on top of it (should be straight-forward), that would be great :)

**Comment by jeanphilippeD** [comment]
Yes, that should not be an issue as soon as it is available in master.
