### ISSUE TITLE
panic when regenerating stylo bindings

### ISSUE THREAD

**Issue by bholley** [servo/rust-bindgen#193]
RUST_BACKTRACE=1 ./regen.py /files/mozilla/repos/rr/obj-x86_64-apple-darwin15.6.0/

CC @nox @fitzgen @emilio

thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:323
stack backtrace:
   1:        0x10c72cf68 - std::sys::backtrace::tracing::imp::write::h22f199c1dbb72ba2
   2:        0x10c730fef - std::panicking::default_hook::{{closure}}::h9a389c462b6a22dd
   3:        0x10c73004f - std::panicking::default_hook::h852b4223c1c00c59
   4:        0x10c730616 - std::panicking::rust_panic_with_hook::hcd9d05f53fa0dafc
   5:        0x10c7304b4 - std::panicking::begin_panic::hf6c488cee66e7f17
   6:        0x10c7303d2 - std::panicking::begin_panic_fmt::hb0a7126ee57cdd27
   7:        0x10c730337 - rust_begin_unwind
   8:        0x10c757ef0 - core::panicking::panic_fmt::h9af671b78898cdba
   9:        0x10c757df4 - core::panicking::panic::h1a2d1a6b50eaa468
  10:        0x10bfef404 - <core::option::Option<T>>::unwrap::h93751f1546d44328
  11:        0x10c0c2aa0 - bindgen::clang::Cursor::is_fully_specialized_template::hee47d51e02a365b1
  12:        0x10c0c2b3a - bindgen::clang::Cursor::is_in_non_fully_specialized_template::hf4316117ec56db74
  13:        0x10c0d730e - bindgen::ir::function::cursor_mangling::hed52fd15c1bc6dbe
  14:        0x10c0e9b6d - <bindgen::ir::var::Var as bindgen::parse::ClangSubItemParser>::parse::hd9a11337b567b0e7
  15:        0x10c0dd77c - <bindgen::ir::item::Item as bindgen::parse::ClangItemParser>::parse::h2412ae46fe0182ed
  16:        0x10c11e072 - bindgen::ir::comp::CompInfo::from_ty::{{closure}}::he6f2b24ed9406dd5
  17:        0x10c0c5da5 - bindgen::clang::visit_children::h278afd2df4ea882d
  18:        0x10d24d163 - _ZN5clang8cxcursor13CursorVisitor5VisitE8CXCursorb
  19:        0x10d24e9f0 - _ZN5clang8cxcursor13CursorVisitor16VisitDeclContextEPNS_11DeclContextE
  20:        0x10d24f367 - _ZN5clang8cxcursor13CursorVisitor18VisitCXXRecordDeclEPNS_13CXXRecordDeclE
  21:        0x10d24f3d5 - _ZN5clang8cxcursor13CursorVisitor43VisitClassTemplatePartialSpecializationDeclEPNS_38ClassTemplatePartialSpecializationDeclE
  22:        0x10d2657a0 - _ZN5clang11declvisitor4BaseINS0_8make_ptrENS_8cxcursor13CursorVisitorEbE5VisitEPNS_4DeclE
  23:        0x10d24da8e - _ZN5clang8cxcursor13CursorVisitor13VisitChildrenE8CXCursor
  24:        0x10d25664c - clang_visitChildren
  25:        0x10c0c4a8e - bindgen::clang::Cursor::visit::hc3e921b6717b33b8
  26:        0x10c0cdfe3 - bindgen::ir::comp::CompInfo::from_ty::h788a93c5aabdec6b
  27:        0x10c0e59af - bindgen::ir::ty::Type::from_clang_ty::h2fafc7cc8df8c243
  28:        0x10c0e0686 - <bindgen::ir::item::Item as bindgen::parse::ClangItemParser>::from_ty_with_id::h25bdf49d0a9501c0
  29:        0x10c0dfb4a - <bindgen::ir::item::Item as bindgen::parse::ClangItemParser>::from_ty::hb7fadceee3c37839
  30:        0x10c0ddda8 - <bindgen::ir::item::Item as bindgen::parse::ClangItemParser>::parse::h2412ae46fe0182ed
  31:        0x10c0ec2fd - bindgen::parse_one::hf9e6ae4a37cbcc8d
  32:        0x10c11cb6b - <bindgen::ir::module::Module as bindgen::parse::ClangSubItemParser>::parse::{{closure}}::{{closure}}::h27aaf1fe946d44b2
  33:        0x10c0c5da5 - bindgen::clang::visit_children::h278afd2df4ea882d
  34:        0x10d24d163 - _ZN5clang8cxcursor13CursorVisitor5VisitE8CXCursorb
  35:        0x10d24e9f0 - _ZN5clang8cxcursor13CursorVisitor16VisitDeclContextEPNS_11DeclContextE
  36:        0x10d26571c - _ZN5clang11declvisitor4BaseINS0_8make_ptrENS_8cxcursor13CursorVisitorEbE5VisitEPNS_4DeclE
  37:        0x10d24da8e - _ZN5clang8cxcursor13CursorVisitor13VisitChildrenE8CXCursor
  38:        0x10d25664c - clang_visitChildren
  39:        0x10c0c4647 - bindgen::clang::Cursor::visit::hba85c6094a75a783
  40:        0x10c11f33b - <bindgen::ir::module::Module as bindgen::parse::ClangSubItemParser>::parse::{{closure}}::hd1827a5568ea21a4
  41:        0x10c0d5dd9 - bindgen::ir::context::BindgenContext::with_module::h3021062e8ff8e1b2
  42:        0x10c0e2c6f - <bindgen::ir::module::Module as bindgen::parse::ClangSubItemParser>::parse::hf724d7ee2aa3af6a
  43:        0x10c0dcd94 - <bindgen::ir::item::Item as bindgen::parse::ClangItemParser>::parse::h2412ae46fe0182ed
  44:        0x10c0ec2fd - bindgen::parse_one::hf9e6ae4a37cbcc8d
  45:        0x10c11cb6b - <bindgen::ir::module::Module as bindgen::parse::ClangSubItemParser>::parse::{{closure}}::{{closure}}::h27aaf1fe946d44b2
  46:        0x10c0c5da5 - bindgen::clang::visit_children::h278afd2df4ea882d
  47:        0x10d24d163 - _ZN5clang8cxcursor13CursorVisitor5VisitE8CXCursorb
  48:        0x10d24e9f0 - _ZN5clang8cxcursor13CursorVisitor16VisitDeclContextEPNS_11DeclContextE
  49:        0x10d26571c - _ZN5clang11declvisitor4BaseINS0_8make_ptrENS_8cxcursor13CursorVisitorEbE5VisitEPNS_4DeclE
  50:        0x10d24da8e - _ZN5clang8cxcursor13CursorVisitor13VisitChildrenE8CXCursor
  51:        0x10d25664c - clang_visitChildren
  52:        0x10c0c4647 - bindgen::clang::Cursor::visit::hba85c6094a75a783
  53:        0x10c11f33b - <bindgen::ir::module::Module as bindgen::parse::ClangSubItemParser>::parse::{{closure}}::hd1827a5568ea21a4
  54:        0x10c0d5dd9 - bindgen::ir::context::BindgenContext::with_module::h3021062e8ff8e1b2
  55:        0x10c0e2c6f - <bindgen::ir::module::Module as bindgen::parse::ClangSubItemParser>::parse::hf724d7ee2aa3af6a
  56:        0x10c0dcd94 - <bindgen::ir::item::Item as bindgen::parse::ClangItemParser>::parse::h2412ae46fe0182ed
  57:        0x10c0ec2fd - bindgen::parse_one::hf9e6ae4a37cbcc8d
  58:        0x10c11c638 - bindgen::parse::{{closure}}::{{closure}}::h09b7000002124f4b
  59:        0x10c0c5da5 - bindgen::clang::visit_children::h278afd2df4ea882d
  60:        0x10d24d163 - _ZN5clang8cxcursor13CursorVisitor5VisitE8CXCursorb
  61:        0x10d24e9f0 - _ZN5clang8cxcursor13CursorVisitor16VisitDeclContextEPNS_11DeclContextE
  62:        0x10d24dcf4 - _ZN5clang8cxcursor13CursorVisitor13VisitChildrenE8CXCursor
  63:        0x10d25664c - clang_visitChildren
  64:        0x10c0c3937 - bindgen::clang::Cursor::visit::h5850f46aa9746ce1
  65:        0x10c11f3b0 - bindgen::parse::{{closure}}::hb529d3637d2c109b
  66:        0x10c0d60cd - bindgen::ir::context::BindgenContext::with_module::h3e7dafc213c4fdac
  67:        0x10c0ec74d - bindgen::parse::h81362f54b82685a9
  68:        0x10c0eae22 - bindgen::Bindings::generate::he8b2821293d41ca0
  69:        0x10bfb7dce - bindgen::main::haa826e8d942fe3dc
  70:        0x10c7315aa - __rust_maybe_catch_panic
  71:        0x10c72fb36 - std::rt::lang_start::h14cbded5fe3cd915
  72:        0x10bfb8669 - main

bindings::None failed

**Comment by fitzgen** [comment]
Interesting so we think that this is a template specialization, but clang thinks that this is not by returning -1 when we ask how many template args there are.

**Comment by bholley** [comment]
40da2112d0682143d1b083c461023446375f7326 is the regressing commit. I just reset my local bindgen to the commit before.

**Comment by fitzgen** [comment]
Fixed in https://github.com/servo/rust-bindgen/commit/ef59d9ed1eeb45494a183c6363069ec492969b34
