### ISSUE TITLE
Incomplete types should generate enums with no variants

### ISSUE THREAD

**Issue by fitzgen** [servo/rust-bindgen#198]
A common pattern is to declare structs/classes in a header, but leave their definition incomplete so that the public API consumers can't manipulate them directly and can only pass pointers/references to API functions that do the heavy lifting. Additionally, API consumers can't construct instances of these incomplete types, and rely on getting pointers to them from other public API functions.

Simple example:

```c++
struct MyDetailsArePrivate;

MyDetailsArePrivate* makeIt();
int publicApiGetter(MyDetailsArePrivate* details);
```

We currently generate Rust bindings like this (trimmed down for brevity):

```rust
#[repr(C)]
#[derive(Debug, Copy)]
pub struct MyDetailsArePrivate {
    pub _address: u8,
}

extern "C" {
    #[link_name = "_Z6makeItv"]
    pub fn makeIt() -> *mut MyDetailsArePrivate;
}
extern "C" {
    #[link_name = "_Z15publicApiGetterP19MyDetailsArePrivate"]
    pub fn publicApiGetter(details: *mut MyDetailsArePrivate)
     -> ::std::os::raw::c_int;
}
```

The way we generate a struct for `MyDetailsArePrivate` means that Rust users can construct instances. This is incorrect, and the false instances are almost assuredly the wrong size, and definitely will contain invalid data. This means that passing pointers to them into FFI functions would be *wildly* unsafe.

If instead we generated an `enum` without any variants, then it would be impossible to construct false instances in Rust, but the FFI functions that take and receive pointers to it would continue to work:

```rust
pub enum MyDetailsArePrivate {
}

extern "C" {
    #[link_name = "_Z6makeItv"]
    pub fn makeIt() -> *mut MyDetailsArePrivate;
}
extern "C" {
    #[link_name = "_Z15publicApiGetterP19MyDetailsArePrivate"]
    pub fn publicApiGetter(details: *mut MyDetailsArePrivate)
     -> ::std::os::raw::c_int;
}
```

**Comment by emilio** [comment]
Yup! This is sort of a duplicate of https://github.com/servo/rust-bindgen/issues/62

**Comment by fitzgen** [comment]
> Yup! This is sort of a duplicate of #62

Ah, so it is!
