### ISSUE TITLE
Travis build time jumped from 20 min to 1h30 min or more

### ISSUE THREAD

**Issue by jeanphilippeD** [servo/rust-bindgen#236]
Hi,

Since PR #214 We build a lot more thing, and build time as jumped from less than 20min to between 1h20min and 2h. https://travis-ci.org/servo/rust-bindgen/builds

Maybe we should limit to a few interesting build (I think this is possible)?

The current matrix for all pull requests and merge commit is, for example:

linux | Rust: stable  | LLVM_VERSION=3.8 BINDGEN_FEATURES=llvm_stable | 10 min 12 sec
-------|------------------|--------------------------------------------------------------------------------|-------------------
linux | Rust: stable  | LLVM_VERSION=3.9 BINDGEN_FEATURES=            |  9 min 42 sec
linux | Rust: nightly | LLVM_VERSION=3.8 BINDGEN_FEATURES=llvm_stable |    9 min 23 sec
linux | Rust: nightly | LLVM_VERSION=3.9 BINDGEN_FEATURES=            |    10 min 52 sec
osx   | Rust: stable  | LLVM_VERSION=3.8 BINDGEN_FEATURES=llvm_stable |    11 min 15 sec
osx   | Rust: stable  | LLVM_VERSION=3.9 BINDGEN_FEATURES=            |    12 min 29 sec
osx   | Rust: nightly | LLVM_VERSION=3.8 BINDGEN_FEATURES=llvm_stable |    12 min 33 sec
osx   | Rust: nightly | LLVM_VERSION=3.9 BINDGEN_FEATURES=            |    12 min 15 sec

Total time 1 hr 28 min 41 sec

**Comment by emilio** [comment]
Yeah, it's sort of painful, I agree... Probably the best way forward is rebasing #70 and get rid of `llvm_stable`, we'd get rid of half of the builds for free.

**Comment by KyleMayes** [comment]
The culprit is that Travis CI has 128 macOS instances for their entire open source service. This results in very long wait times for macOS builds.

**Comment by tschneidereit** [comment]
> The culprit is that Travis CI has 128 macOS instances for their entire open source service. This results in very long wait times for macOS builds.

We should get this on paid instances, then. @larsbergstrom can we do that?

**Comment by larsbergstrom** [comment]
@tschneidereit Travis is looking currently working to expand the number of macOS instances available. I'll try to get an update on that timeline. They do not have any publicly announced options for reserved paid instances.

**Comment by tschneidereit** [comment]
Ah, that's unfortunate. Let's hope they get more instances online soon,
then.

**Comment by fitzgen** [comment]
> Total time 1 hr 28 min 41 sec

I'm sure everyone knows this, but I want to spell it out: this is *not* wall time, the builds can (and mostly do) run in parallel.

> very long wait times for macOS builds

This is our bottleneck.

Perhaps we should disable the OSX builds until we can get a paid instance or they add more to their cluster?

**Comment by jdub** [comment]
Some of the changes in #204 and #265 should help with this a bit.

**Comment by KyleMayes** [comment]
Unfortunately, as @fitzgen said, the issue is not the build times themselves, but the long wait times for macOS builds. This is a Travis CI issue, not one that can be fixed here.

**Comment by emilio** [comment]
I think this can be closed since we can't do much about it, and there are a few PRs that make build times acceptable. Feel free to reopen if you disagree or think that some action needs to be taken :)
