### ISSUE TITLE
Support rust-bindgen in Cargo.tml?

### ISSUE THREAD

**Issue by kkimdev** [servo/rust-bindgen#241]
I think it would be nice if a project that uses rust-bindgen can include it in their Cargo.tml, for example:

[build-dependencies.bindgen]
git = "https://github.com/servo/rust-bindgen"
features = ["llvm_stable"]

But one problem is that then Cargo does not build ./bindgen binary, but only lib.rs.  I'm not sure what's would be a proper way of solving this problem yet though.

**Comment by emilio** [comment]
I think the idea for this is to use the library and invoke it from `build.rs`. Could you elaborate what kind of use case could require the binary?

I'm not sure cargo support binaries in build-dependencies out of the box :/

**Comment by kkimdev** [comment]
Yes right, but actually, I guess we don't need the binary and just can call the library directly from `build.rs`...
