### ISSUE TITLE
Can't find system headers

### ISSUE THREAD

**Issue by dimbleby** [servo/rust-bindgen#242]
/usr/include/sys/types.h:146:10: fatal error: 'stddef.h' file not found
    /usr/include/sys/types.h:146:10: fatal error: 'stddef.h' file not found, err: true

Looks like you go to the trouble of figuring out where to look - https://github.com/servo/rust-bindgen/blob/bdfab643e70df469dd0d163cc91bf48955250735/src/bin/bindgen.rs#L64-L67 - and then forget all about it! - https://github.com/servo/rust-bindgen/blob/bdfab643e70df469dd0d163cc91bf48955250735/src/bin/bindgen.rs#L73.

I think the fix is simply:

    -    match builder_from_flags(env::args()) {
    +    match builder_from_flags(bind_args.into_iter()) {

**Comment by emilio** [comment]
Pfft, right, cc @jdub, sorry for missing this while reviewing #228. Thanks for filing this!

**Comment by jdub** [comment]
D'oh! Nice catch.

**Comment by brunoqc** [comment]
I have a similar problem:
```
/usr/include/gssapi/gssapi.h:63:10: fatal error: 'stddef.h' file not found, err: true
```

bindgen: 0.20.2
rustc 1.16.0-nightly (83c2d9523 2017-01-24)
clang/llvm: 3.9.1
Ubuntu 16.04.1 LTS (64-bit)

**Comment by emilio** [comment]
This is on 64 bit? Huh, in any case, this is a different issue (a check that exists was broken), may you fill a new issue with the output of `clang -E - -v`?

**Comment by brunoqc** [comment]
It wasn't a bug after all. I was missing the `clang-3.9` package. I thought `llvm-3.9-dev` and  `libclang-3.9-dev` were enough (I had llvm-config-3.9). It was on 64 bit. Thanks.

**Comment by virtualritz** [comment]
I have the same issue as @dimbleby. I'm on macOS 10.13.6, latest command line tools installed.
When trying to generate any C++ bindings through bindgen (0.41.0) I get:
```
/Library/Developer/CommandLineTools/usr/include/c++/v1/cstddef:44:15: fatal error: 'stddef.h' file not found
/Library/Developer/CommandLineTools/usr/include/c++/v1/cstddef:44:15: fatal error: 'stddef.h' file not found, err: true
thread 'main' panicked at 'Unable to generate 3Delight bindings: ()', libcore/result.rs:1009:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

Generating C bindings works fine. I tried with several different C++ headers. I always get this error.
The resp. header is present on my system in many locations:
```
$ locate stddef.h
/Library/Developer/CommandLineTools/Library/PrivateFrameworks/LLDB.framework/Versions/A/Resources/Clang/include/stddef.h
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Kernel.framework/Versions/A/Headers/stddef.h
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/stddef.h
/Library/Developer/CommandLineTools/usr/include/c++/v1/stddef.h
/Library/Developer/CommandLineTools/usr/lib/clang/10.0.0/include/stddef.h
/Library/Developer/CommandLineTools/usr/lib/tapi/10.0.0/include/stddef.h
/System/Library/Frameworks/Kernel.framework/Versions/A/Headers/stddef.h
/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/2.0/include/stddef.h
/System/Library/PrivateFrameworks/GPUCompiler.framework/Versions/A/Libraries/lib/clang/3.5/include/stddef.h
/usr/include/stddef.h
/usr/local/Cellar/boost/1.67.0_1/include/boost/asio/detail/cstddef.hpp
```

**Comment by chibby0ne** [comment]
> It wasn't a bug after all. I was missing the `clang-3.9` package. I thought `llvm-3.9-dev` and `libclang-3.9-dev` were enough (I had llvm-config-3.9). It was on 64 bit. Thanks.

More generally, the standard headers used by rust-bindgen are provided by the `clang-VER` package in newer Ubuntu distros, where `VER` is the major version of clang/llvm.
