### ISSUE TITLE
Debug derived when not allowed

### ISSUE THREAD

**Issue by dimbleby** [servo/rust-bindgen#246]
Eg change `tests/headers/union_with_big_member.h` like this:

    -  int b[33];
    +  char b[33];

Then the output is like this:

```rust
#[repr(C)]
#[derive(Debug, Copy)]
pub struct WithBigArray {
    pub a: __BindgenUnionField<::std::os::raw::c_int>,
    pub b: __BindgenUnionField<[::std::os::raw::c_char; 33usize]>,
    pub bindgen_union_field: [u32; 9usize],
}
```

But the array `b` of __BindgenUnionField` is too large for `#[derive(Debug)]` to be allowed.

I hit this with a header file that pulls in `pthreads`: in particular

````c
union pthread_attr_t
{
  char __size[__SIZEOF_PTHREAD_ATTR_T];
  long int __align;
};
````

**Comment by dimbleby** [comment]
Actually on closer inspection I see that `b` isn't an array at all.  But still, the compiler complains like this:

```
error[E0277]: the trait bound `[i8; 56]: std::fmt::Debug` is not satisfied
   --> src/ffi.rs:712:5
    |
712 |     pub __size: __BindgenUnionField<[::std::os::raw::c_char; 56usize]>,
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `std::fmt::Debug` is not implemented for `[i8; 56]`
    |
    = note: `[i8; 56]` cannot be formatted using `:?`; if it is defined in your crate, add `#[derive(Debug)]` or manually implement it
    = note: required because of the requirements on the impl of `std::fmt::Debug` for `ffi::__BindgenUnionField<[i8; 56]>`
    = note: required because of the requirements on the impl of `std::fmt::Debug` for `&ffi::__BindgenUnionField<[i8; 56]>`
    = note: required for the cast to the object type `std::fmt::Debug`
```

(that output taken from compiling the pthreads example)

**Comment by dimbleby** [comment]
By the way, I'd actually prefer not to generate Rust code to match pthreads headers at all - is there a way of excluding such things from the output?

**Comment by emilio** [comment]
@dimbleby yup! You can pass `--whitelist` flags with a regex, and we'll only generate stuff that match that regex, or are used by it recursively.

Thanks for the report! This should be fixed in #248.

**Comment by emilio** [comment]
One of the pending stuff is writing better documentation in how to filter stuff, I use to point to Stylo's (Servo's style system in Gecko) script, but that's become really complex lately, so I'd rather write generic documentation :)

**Comment by dimbleby** [comment]
gotcha thanks - and thanks for the impressively quick turnaround on the bug reports!

**Comment by emilio** [comment]
No problem! And thank _you_ for reporting them! :)
