### ISSUE TITLE
Panic at `TranslationUnit::parse`

### ISSUE THREAD

**Issue by azerupi** [servo/rust-bindgen#249]
I tried to run bindgen on the [openfx header files](https://github.com/ofxa/openfx/tree/master/include) but I got a panic:

```
$ bindgen include/*.h                           
thread 'main' panicked at 'TranslationUnit::parse', ../src/libcore/option.rs:705
stack backtrace:
   1:     0x5589ab76be4f - std::sys::backtrace::tracing::imp::write::h6f1d53a70916b90d
   2:     0x5589ab77112d - std::panicking::default_hook::{{closure}}::h137e876f7d3b5850
   3:     0x5589ab77004a - std::panicking::default_hook::h0ac3811ec7cee78c
   4:     0x5589ab7705e8 - std::panicking::rust_panic_with_hook::hc303199e04562edf
   5:     0x5589ab770482 - std::panicking::begin_panic::h6ed03353807cf54d
   6:     0x5589ab7703c0 - std::panicking::begin_panic_fmt::hc321cece241bb2f5
   7:     0x5589ab770341 - rust_begin_unwind
   8:     0x5589ab7a7c8f - core::panicking::panic_fmt::h27224b181f9f037f
   9:     0x5589ab7a7d05 - core::option::expect_failed::h8606bc228cd3f504
  10:     0x5589ab4b737d - bindgen::ir::context::BindgenContext::new::hbb87c6d36471e05f
  11:     0x5589ab4ca0b0 - bindgen::Bindings::generate::h874f52036a1239e0
  12:     0x5589ab4c9d94 - bindgen::Builder::generate::hd73069614a30fa2a
  13:     0x5589ab432210 - bindgen::main::hace8f155f8b5cece
  14:     0x5589ab778bf6 - __rust_maybe_catch_panic
  15:     0x5589ab76f8c1 - std::rt::lang_start::h538f8960e7644c80
  16:     0x7f0bc867a290 - __libc_start_main
  17:     0x5589ab415319 - _start
  18:                0x0 - <unknown>

```

**EDIT:** I tried to run bindgen on every file individually, but I can't reproduce it that way...

**Comment by emilio** [comment]
Yes, bindgen right now doesn't support throwing multiple files at it directly. This in this case is somewhat silly because we can't sort the files for you, and files have dependencies between them.

The way to do it is either creating a master header file with the appropriate includes:

```c
// all.h
#include "include/ofxCore.h"
// (and so on...)
```

Or using the `-include` clang flag in the appropriate order.

```
$ ./bindgen include/ofxCore.h -- -include "ofxFoo.h" -include "ofxBar.h" ...
```

I guess we can try to enhance the use, or at least the error message though, so leaving it open...

**Comment by azerupi** [comment]
Oh right, my bad.. it does sound silly now that you say it.

I wonder, would it be possible for bindgen to create that "master file" including all the headers itself? Does order really matter if you include them all anyway? It could even be a temporary file so that it doesn't leave any artifacts

A better error message would be great! :)

**Comment by emilio** [comment]
Hmm... I don't think it's possible for bindgen to make the "master header" in the general case. There are definitely dependencies between headers. Usually not many in public APIs, but still existing.

**Comment by azerupi** [comment]
> There are definitely dependencies between headers.

It's been a long time since I have done any C / C++ but, assuming the headers have header guards preventing double inclusion, what other problems could there be?

**Comment by jtojnar** [comment]
I got this error by accidentally omitting `>` for redirecting output (`bindgen header.h  bindings.rs`). Showing a better error message would be nice.

**Comment by fitzgen** [comment]
We support multiple headers now.
