### ISSUE TITLE
Constructor support.

### ISSUE THREAD

**Issue by kkimdev** [servo/rust-bindgen#250]
Please correct me if I'm wrong, but looks like we don't support constructor yet?

**Comment by emilio** [comment]
Yep, that's right. I'm not sure what calling convention do compilers use for constructors, and similar, so right now they aren't parsed.

I haven't (nor plan in the short term) tried to figure out a way to call a C++ constructor from rust directly. Hopefully they use something like placement new under the hood and we can call them, but...

**Comment by brunoqc** [comment]
Was this implemented with #332?

**Comment by emilio** [comment]
Right.
