### ISSUE TITLE
With replacements, we can generate a use of a type w/ no definition for that type

### ISSUE THREAD

**Issue by fitzgen** [servo/rust-bindgen#251]
`creduce` ftw! \o/

Flags: `--whitelist-type Rooted -- --std=c++14`

Input:

```c++
template <typename a> using MaybeWrapped = a;
class Rooted {
  MaybeWrapped<int> ptr;
};
/// <div rustbindgen replaces="MaybeWrapped"
template <typename a> using replaces_MaybeWrapped = a;
```

Output:

```rust
/* automatically generated by rust-bindgen */

#[repr(C)]
#[derive(Debug, Copy)]
pub struct Rooted {
    pub ptr: MaybeWrapped<a>,
}
#[test]
fn bindgen_test_layout_Rooted() {
    assert_eq!(::std::mem::size_of::<Rooted>() , 4usize);
    assert_eq!(::std::mem::align_of::<Rooted>() , 4usize);
}
impl Clone for Rooted {
    fn clone(&self) -> Self { *self }
}
```

Note how `MaybeWrapped` is used, but never defined. The `<a>` tells me we are probably treating it as a named template argument.

**Comment by fitzgen** [comment]
Hmmm.... somehow we end up with a field whose `ty == ItemId(7)`, however we **never** `BindgenContext::add_item(item)` where `item.id == ItemId(7)`. Looks like this is another dangling id issue...

**Comment by fitzgen** [comment]
Ah nevermind, it's just our logging that was incomplete. Looks like it is being added as a builtin type:

```
DEBUG:bindgen::ir::context: add_builtin_item: item = Item { id: ItemId(7), local_id: Cell { value: None }, next_child_local_id: Cell { value: 1 }, canonical_name_cache: RefCell { value: None }, comment: None, annotations: Annotations { opaque: false, hide: false, use_instead_of: None, disallow_copy: false, private_fields: None, accessor_kind: None }, parent_id: ItemId(6), kind: Type(Type { name: Some("MaybeWrapped<int>"), layout: Some(Layout { size: 4, align: 4, packed: false }), kind: ResolvedTypeRef(ItemId(4)), is_const: false }) }
```

**Comment by fitzgen** [comment]
* The field has `ty: ItemId(7)`

* `ItemId(7)` is a `ResolvedTypeRef(ItemId(4))`

* `ItemId(4)` is an `Alias("MaybeWrapped", ItemId(5))`

* `ItemId(5)` is a `UnresolvedTypeRef(Type(a, kind: Unexposed, decl: Cursor( kind: NoDeclFound, loc: builtin definitions, usr: None), canon: Cursor( kind: NoDeclFound, loc: builtin definitions, usr: None)), Some(Cursor(MaybeWrapped kind: TypeAliasDecl, loc: RootingAPI.hpp:1:29, usr: Some("c:@MaybeWrapped"))), Some(ItemId(1)))`

This last point seems to be where we go wrong. We should be creating a named type for `ItemId(5)` instead of an `UnresolvedTypeRef`.

**Comment by emilio** [comment]
Note that the unresolved types change before processing both replacements
and whitelisting, so you should probably take a look at the state of the
context after "resolve_typerefs".

Thanks for digging into this! :)

**Comment by fitzgen** [comment]
This is actually fixed -- thanks @emilio  :)
