### ISSUE TITLE
publish rust-bindgen to crates.io

### ISSUE THREAD

**Issue by froydnj** [servo/rust-bindgen#252]
Firefox has a mechanism for importing crates into its source tree, which depends on `cargo vendor`.  `cargo vendor`, in turn, expects everything to be published on `crates.io`.  (Yes, yes, we could point it at a different crate registry, but that has its own set of problems.)  `rust-bindgen` will eventually need to be imported into mozilla-central so that `rust-bindgen` can be run on every build.

Ergo, it would be splendid if `rust-bindgen` were published to `crates.io` so the import could be accomplished with minimal hassle.

**Comment by heycam** [comment]
Maybe #21 needs to be solved first.

**Comment by emilio** [comment]
Probably we can publish as `servo-bindgen`, at least in the meantime. I'll do that today.

**Comment by emilio** [comment]
Actually, probably it's a better idea to wait for https://github.com/servo/rust-bindgen/pull/204 to land.

**Comment by darfink** [comment]
Would it be possible to publish this now, since #204 has landed?

**Comment by emilio** [comment]
Yes, I'm still fixing some fallout from recent changes, but when it's
stable enough I'll publish it.

**Comment by fitzgen** [comment]
After #327 I thought we would be good to publish `libbindgen` on crates.io, but I'm getting this error:

```
$ cargo publish
   Verifying libbindgen v0.1.0 (file:///home/fitzgen/src/rust-bindgen/libbindgen)
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling regex-syntax v0.3.9
   Compiling log v0.3.6
   Compiling unicode-xid v0.0.3
   Compiling utf8-ranges v0.1.3
   Compiling rustc-serialize v0.3.22
   Compiling winapi v0.2.8
   Compiling lazy_static v0.1.16
   Compiling nom v1.2.4
   Compiling cfg-if v0.1.0
   Compiling winapi-build v0.1.1
   Compiling glob v0.2.11
   Compiling bitflags v0.7.0
   Compiling libc v0.2.18
   Compiling kernel32-sys v0.2.2
   Compiling term v0.4.4
   Compiling memchr v0.1.11
   Compiling thread-id v2.0.0
   Compiling cexpr v0.2.0
   Compiling thread_local v0.2.7
   Compiling aho-corasick v0.5.3
   Compiling clang-sys v0.11.1
   Compiling regex v0.1.80
   Compiling syntex_pos v0.44.0
   Compiling syntex_errors v0.44.0
   Compiling syntex_syntax v0.44.1
   Compiling env_logger v0.3.5
   Compiling syntex v0.44.0
   Compiling quasi v0.21.0
   Compiling aster v0.29.0
   Compiling quasi_codegen v0.21.0
   Compiling libbindgen v0.1.0 (file:///home/fitzgen/src/rust-bindgen/libbindgen/target/package/libbindgen-0.1.0)
    Finished debug [unoptimized + debuginfo] target(s) in 64.71 secs
   Uploading libbindgen v0.1.0 (file:///home/fitzgen/src/rust-bindgen/libbindgen)
error: api errors: invalid upload request: ApplicationError("invalid crate name specified: _docs")
```

I think `cargo` doesn't like that we have a feature with a leading underscore?

**Comment by emilio** [comment]
Libbindgen is published now at https://crates.io/crates/libbindgen :)

Stylo is going to need to use it from there. @darfink let me know if you also want the binary published.
