### ISSUE TITLE
Support for macro defined string constants

### ISSUE THREAD

**Issue by azerupi** [servo/rust-bindgen#256]
I am trying to make bindings for the OpenFX API and they define some constants using macros:

```c
#define kOfxImageEffectPluginApi "OfxImageEffectPluginAPI"
#define kOfxImageEffectPluginApiVersion 1
```

Bindgen seems to have no trouble with the numeric constant, but it ignores the string constant. Would it be possible to add support for macro defined string constants?

**Comment by emilio** [comment]
Patch up in #260, with a bunch of other improvements.

**Comment by azerupi** [comment]
That was fast! Thank you :)
