### ISSUE TITLE
Large unsigned integer literal is generated to signed literal

### ISSUE THREAD

**Issue by upsuper** [servo/rust-bindgen#274]
Another issue apart from #272. Having the following code
```c++
typedef unsigned long uint32_t;
const uint32_t k = 0x80000000U;
```
it generates
```rust
pub const k: u32 = -2147483648;
```
which is clearly wrong.

**Comment by emilio** [comment]
This seems like an overflow happening directly in libclang, that returns an `int`. I guess we can check if the signedness matches and act properly (either converting, or generating nothing).

I can fix this tomorrow morning if you haven't already :)

**Comment by upsuper** [comment]
I haven't.

It doesn't seem to me it is easy to check overflow. Probably we should just ignore evaluation from clang and parse integer literals ourselves... But that would make things like `1 << 10` not work, which seems unfortunate as well.

**Comment by emilio** [comment]
It's not easy to check unfortunately, but we can prevent invalid code easily at least.

**Comment by upsuper** [comment]
Probably we should also bug libclang to add a better API... but registeration to their bugzilla is closed :/

**Comment by emilio** [comment]
I have an account and I've sent a few patches already, I should be able to send one for this.

**Comment by emilio** [comment]
https://reviews.llvm.org/D26788

**Comment by upsuper** [comment]
Probably makes more sense if it can return a string of the evaluate result, so that it can be extended to whatever length in the future... but probably that's overkill.
