### ISSUE TITLE
error: expected identifier, found keyword `type`

### ISSUE THREAD

**Issue by comex** [servo/rust-bindgen#278]
When running bindgen on the following definition:
```
typedef struct
{
  natural_t             pad1;
  mach_msg_size_t       pad2;
  unsigned int                pad3 : 24;
  mach_msg_descriptor_type_t  type : 8;
} mach_msg_type_descriptor_t;
```
the resulting code includes `pub fn type(&self)`, which is invalid.

**Comment by emilio** [comment]
Gah, good catch, missed the name mangling in the getter name, should be fixed in #279.

Thanks for the report! :)
