### ISSUE TITLE
Whitelist type is not working as expected

### ISSUE THREAD

**Issue by upsuper** [servo/rust-bindgen#300]
Given the following code:
```c++
struct Test {};
extern "C" void Servo_Test(Test* a);
```
with command `cargo run -- test.hpp --no-unstable-rust --whitelist-function 'Servo_.*' -- -x c++ -std=c++14`, rust-bindgen generates:
```rust
#[repr(C)]
#[derive(Debug, Copy)]
pub struct Test {
    pub _address: u8,
}
#[test]
fn bindgen_test_layout_Test() {
    assert_eq!(::std::mem::size_of::<Test>() , 1usize);
    assert_eq!(::std::mem::align_of::<Test>() , 1usize);
}
impl Clone for Test {
    fn clone(&self) -> Self { *self }
}
extern "C" {
    pub fn Servo_Test(a: *mut Test);
}
```

I think the struct `Test` is not supposed to be there, as it is not whitelisted.

We rely on this for bindings.rs since otherwise it would have lots of overlap types with structs.

**Comment by emilio** [comment]
This is expected, since `Test` is in the signature of `Servo_Test`. The solution to that is blacklist `Test`.

**Comment by upsuper** [comment]
I guess that solution works, although probably the behavior is different from before. I guess it is better there is some document describes the interaction between whitelist and blacklist.

**Comment by emilio** [comment]
Yes, that changed in https://github.com/servo/rust-bindgen/commit/bd29a7a86ec9b7a2666fe290da940e319e71b008, in general I don't think that was expected to work, but yeah, a few more docs will help.
