### ISSUE TITLE
Potential whitelisting/replacements/etc name conflicts

### ISSUE THREAD

**Issue by fitzgen** [servo/rust-bindgen#306]
We use namespace mangled names for name checking, but these could conflict with other real names of things.

For example, if I wanted to whitelist only one or the other struct here, how would I do that? `--whitelist-type JS_Foo` is how you would refer to both of these types, but both would match, so you couldn't single one out.

```c++
namespace JS {
  struct Foo { };
}

struct JS_Foo { };
```

Not sure what to do here. Perhaps name checking should work on C++ names w/ namespaces? So `JS::Foo` would be the first struct and `JS_Foo` would be the second.

This is a mess...

Thoughts @emilio ?

**Comment by emilio** [comment]
To recapitulate what was discussed on IRC yesterday... Yes, I'm all-in to allow only `--enable-cxx-namespaces`, but I need to be sure its state is suitable for stylo at least.

With that, we can probably allow whitelisting with `JS::Foo`, for example, and use the canonical path to match those.

**Comment by fitzgen** [comment]
What if we only support `--enable-cxx-namespaces`? I think this is what we want 99.9999% of the time anyways...

WDYT @emilio ?

**Comment by fitzgen** [comment]
Err... I thought this was abotu name clashes in the codegen. We use `JS::Foo` names for whitelisting and all that now, so this issue can close.
