### ISSUE TITLE
With --enable-cxx-namespaces, can't use bindings in submodule within crate

### ISSUE THREAD

**Issue by fitzgen** [servo/rust-bindgen#308]
Or else the various `use root;` statements don't match the path they need to, which would be `use self::root;` I think.

This is rather frustrating, and means I have to use `include!(bindings.rs)` in the crate's `lib.rs` instead of `mod bindings;` to maintain some semblance of file tidiness/separation.

I am unsure what a fix would look like. Ideas?

**Comment by emilio** [comment]
I'm duping this with #96, but feel free to comment there. Shouldn't be hard to fix.
