### ISSUE TITLE
libbindgen fails with "How?"

### ISSUE THREAD

**Issue by Nashenas88** [servo/rust-bindgen#353]
The following code:
```c
typedef void (Tcl_FSDupInternalRepProc) ();
extern Tcl_FSDupInternalRepProc TclNativeDupInternalRep;
```

Triggers the "How?" panic in `libbindgen/src/codegen/mod.rs:2008` reproduced here:
```rust
        let signature = match *signature.kind() {
            TypeKind::Function(ref sig) => sig,
            _ => panic!("How?"), // << This line
        };
```

Changing it to:
```rust
        let signature = match *signature.kind() {
            TypeKind::Function(ref sig) => sig,
            ref ty => panic!("How? {} {:?}", name, ty), // << This line
        };
```

Outputs: `How? TclNativeDupInternalRep ResolvedTypeRef(ItemId(1))`

I was hoping to use libbindgen to move away from Tcl without needed to jump to C++, but the above declaration style is used all over the Tcl headers. (It's of course been cleaned up, macros and extra typedefs removed).

**Comment by fitzgen** [comment]
Thanks for the bug report!
