### ISSUE TITLE
Replace all non-fatal `error!`s with `warn!`s

### ISSUE THREAD

**Issue by fitzgen** [servo/rust-bindgen#368]
Right now, we use `error!("blah blah")` to log a bunch of errors that are non-fatal: we know something is fishy, but not fishy enough to give up on generating bindings completely. These get logged by default and show up as 

```
ERROR:bindgen::foo::bar: blah blah blah
```

on our users' terminals. This can be scary to users, and make them think something has gone horribly wrong, when probably everything is OK-ish if we generated bindings successfully.

We should replace all non-fatal `error!`s with `warn!`s to make them less scary.

Would love to mentor someone on this good first bug.

Steps to fixing are basically:

* Evaluate each use of the `error!` macro
    * If it is followed by returning an `Err(...)`, then leave it as-is (it is logging for some error that made us give up whatever we were doing)
    * Otherwise, replace it with a `warn!` instead

**Comment by saneyuki** [comment]
Can I take this?

**Comment by fitzgen** [comment]
Sure thing! Let me know if you have any questions!
