### ISSUE TITLE
Figure out a way to quiet test expectations' warning spew

### ISSUE THREAD

**Issue by fitzgen** [servo/rust-bindgen#373]
They are so noisy with style warnings (eg camel case and capitalization) that we expect to fail. Makes reading the test results harder than it should be.

Perhaps we should insert

```rust
#![allow(non_camel_case)]; // or whatever the exact incantation is
// etc...
```

by default?

**Comment by emilio** [comment]
It should be easy to just insert that in the test results with `raw_line`, or in the module, right/

**Comment by fitzgen** [comment]
While we can easily do this with `raw_line`, I wanted to avoid

* editing every test header manually
* doing something specific that pretty much every general usage of bindgen wants to have

Therefore, I think we should put this in the codegen for modules (or only the top level module?)

**Comment by emilio** [comment]
I meant `raw_line` not as a flag in each test file, but as a configuration option in the builder, as we do for a few other things like `no_unstable_rust`.

I'm fine if we want to make it default I guess, but raw_line is easy to use and powerful enough to allow people choose whatever they want.

**Comment by emilio** [comment]
This is partially fixed in our tests, and we have other issues tracking the remaining work, if any.

**Comment by jpochyla** [comment]
Sorry to dig into such an old issue, but how are bindgen users supposed to deal with this?
