### ISSUE TITLE
Only PRs (not issues) arrive to IRC.

### ISSUE THREAD

**Issue by emilio** [servo/rust-bindgen#375]
I don't know what's needed to tweak this, but I hope it should be straight-forward.

I don't think I have access to do it, maybe @jdm or @larsbergstrom can?

**Comment by larsbergstrom** [comment]
I'm not really sure how that happens, tbh. The settings are nearly identical for the IRC integration between this one and servo/servo (which does have the issues notifications), except that the Servo one only tracks changes to the `master` branch. Maybe those notifications are coming in via another service (e.g., highfive)? Hard to know, as the `ghservo` irc nic doesn't have a password, so it could be anything that's hooked up to the servo/servo webhooks.

**Comment by jdm** [comment]
I've noticed that the IRC webhook doesn't appear to work properly for repositories that were transfered from some user to the servo organization. This is the same problem that happens for highfive and webrender, among others.

**Comment by emilio** [comment]
Closing issues seems to work now, I think opening them too.
