### ISSUE TITLE
--link* options don't do anything

### ISSUE THREAD

**Issue by jsgf** [servo/rust-bindgen#376]
`--link`, `--framework-link` and `--static-link` are parsed and put into `BindgenOptions::links`, but as far as I can tell nothing does anything with them after that.

Presumably the intent is to generate a set of `#[link ...]` directives before the `extern "C" { ... }`?

**Comment by emilio** [comment]
Yes, this is a dupe of #104.

TLDR, I'm not sure it's bindgen's business, but if you give me a use-case you can't solve cleanly and needs bindgen to support it, I'd be happy to add them back.

**Comment by emilio** [comment]
(Cleanly as: using either `--raw-line` from bindgen's CLI, or the standard cargo build script foo if used in a build script).

Closing as a dupe, feel free to comment over #104 :)
