### ISSUE TITLE
C++ decltype syntax leaking into Rust code

### ISSUE THREAD

**Issue by jsgf** [servo/rust-bindgen#381]
This input:
```c++
namespace std
{
  typedef char string;
    template < typename _Alloc > struct allocator_traits
  {
    typedef decltype ( _S_size_type_helper ( ( _Alloc * ) 0 ) ) __size_type;
  };
}
namespace __gnu_cxx
{
  template < typename _Alloc > struct __alloc_traits:std::allocator_traits <
    _Alloc >
  {
  };
}
namespace std
{
  template < typename, typename _Alloc > struct _Vector_base
  {
    __gnu_cxx::__alloc_traits < _Alloc > _Tp_alloc_type;
  };
  template < typename _Tp, typename _Alloc = _Tp > class vector:_Vector_base < _Tp,
    _Alloc >
  {
  };
  class LogMessage
  {
    class ostrstream
    {
      union
      {
        vector < string > *outvec_;
      };
    };
  };
}
```

Causes bindgen to leak C++ syntax into the output file:
```rust
pub type std_allocator_traits___size_type =
    decltype(_S_size_type_helper((_Alloc *)0));
```

Command line:
```
bindgen --no-unstable-rust --output decltype.rs decltype.i -- -x c++ -std=gnu++14
```
Full output: https://gist.github.com/jsgf/c0276dfe4a004ead79157a287eef4aa7

**Comment by emilio** [comment]
Yeah, this is mostly a subtle consequence of #362. Arguably we should detect those (I think we already have some code for doing that for `typename`, so it might not be hard), and at least avoid generating code for those types.

Thanks for reporting again :)

**Comment by fitzgen** [comment]
Regarding detection: rather than checking if "typename" is in the named type, we should just check that the named type is a valid identifier.

**Comment by emilio** [comment]
This should be fixed now, thanks for reporting :)

**Comment by fusepilot** [comment]
I tried his example just now on 0.20.5 and got the exact same output as he posted before.

**Comment by emilio** [comment]
Yes, it's not published yet

**Comment by emilio** [comment]
We need to bump version + new release, but I usually close bugs when they're fixed on master.
