### ISSUE TITLE
Need a way to specify codegen behavior for enum items

### ISSUE THREAD

**Issue by upsuper** [servo/rust-bindgen#392]
In `nsCSSPropertyID` enum, we have something like:
```c++
enum nsCSSPropertyID {
  eCSSProperty_a,
  eCSSProperty_b,
  // ...

  eCSSProperty_COUNT,
  eCSSProperty_COUNT_DUMMY2 = eCSSProperty_COUNT - 1,

  eCSSPropertyAlias_aa,
  eCSSPropertyAlias_bb,
  // ...
}
```

In this case, since `eCSSPropertyAlias_aa` would be identical to `eCSSProperty_COUNT`, it would become a separate constant rather than an enum item. This is undesired. Ideally, `eCSSProperty_COUNT` should become a constant, while `eCSSPropertyAlias_aa` should be an enum item.

I guess we can add something like
```c++
/// <div rustbindgen constant></div>
```
to bindgen to correct this kind of cases.

**Comment by emilio** [comment]
Fixed by #393 :)
