### ISSUE TITLE
Publish the executable on crates.io

### ISSUE THREAD

**Issue by kkimdev** [servo/rust-bindgen#398]
Since this is a useful library that is used in also many non-servo projects, I think it will be convinient to have it in crates.io.  Then also we can do `cargo install servo-rust-bindgen` .

**Comment by emilio** [comment]
So the library part of this is published as libbindgen at:

https://crates.io/crates/libbindgen

If you think the executable would also be helpful, please let me know, I
think we can publish it too :)

**Comment by kkimdev** [comment]
Oh, didn't know that. :). Not a big deal but executable will be little more convenient for me too, as normally I first need to use command line `bindgen` and try different options to make it actually work.

**Comment by emilio** [comment]
I think at this point we should also publish the executable. I guess the ideal name would be `bindgen`, but I don't know...

@Yamakaky, from skimming a few issues at https://github.com/Yamakaky/rust-bindgen, it seems really broken in newer libclang versions. Do you think we should finally coalesce both repos into this one and close #21?

**Comment by Yamakaky** [comment]
I think so. I don't remember, are there still features missing compared to the other repo?
My main concern was also the requirement for a clang 3.9, even if you only use C.

**Comment by emilio** [comment]
That's no longer the case since quite a while ago (#335). Now we should be able to use virtually any libclang version.

**Comment by Yamakaky** [comment]
What should we do on crates.io then? Use `bindgen` for lib+bin, `bindgen` for bin and `libbindgen` for lib, something else? If we do the second, it may be confusing for current users of the upstream library.

**Comment by emilio** [comment]
Ok, so I replied by email here and it got lost apparently, sorry.

I think if the bindgen name becomes available we should use it, probably deprecating the name `libbindgen` or something.

We can't just remove libbindgen from crates.io because servo and Gecko uses it, but it seems reasonable to switch crates for an update.

**Comment by Yamakaky** [comment]
Sure then. Could you make sure semver of your fork > semver of upstream ?
Also, could you add me to this repo?

**Comment by emilio** [comment]
Yeah, it's going to require a bit more work because we need to "unsplit" the crates, but meanwhile I've added you as a collaborator to this repo.

**Comment by Yamakaky** [comment]
Cool. I also added you to upstream, it will be easier.

**Comment by fitzgen** [comment]
I think that moving forward we should ensure that we continue to have @bors-servo (and @highfive) support for the canonical bindgen repo. Maybe that means it is easier to use servo/rust-bindgen as the canonical repo, or maybe getting @bors-servo on non-servo org repos is easy enough.

**Comment by fitzgen** [comment]
I agree that it is definitely time we merged forks :)

**Comment by emilio** [comment]
My idea was be making this repo the canonical one tbh. Is that any concern?

**Comment by Yamakaky** [comment]
I'm good with that.

**Comment by fitzgen** [comment]
+1

**Comment by fitzgen** [comment]
@Yamakaky can you also add me and @emilio to the crates.io owners? http://doc.crates.io/crates-io.html#cargo-owner

Thanks!

**Comment by Yamakaky** [comment]
Done

**Comment by fitzgen** [comment]
What is left to complete the unforking?

All I can think of is:

* Make servo/rust-bindgen not have "forked from Yamakaky/rust-bindgen" anymore

**Comment by Yamakaky** [comment]
also, add a depreciation warning on upstream.

**Comment by emilio** [comment]
@fitzgen I think we need to contact github for that, do you mind doing that? Otherwise I can do it.

**Comment by tschneidereit** [comment]
I think we should at least consider moving it under the rust-lang org. I know that there's at least tentative interest in doing that. Not sure whom best to talk to from the Rust team about that.

**Comment by emilio** [comment]
I guess that works, though right now we depend on bors-servo for CI, and transferring a repo when there's no fork it's straight-forward (so it can be discussed and done later without the need to contact GitHub).

**Comment by tschneidereit** [comment]
> transferring a repo when there's no fork it's straight-forward

That's a good point. It makes sense to do this now, and pursue a move to rust-lang afterwards.

**Comment by fitzgen** [comment]
I think we need to do something like http://stackoverflow.com/a/17366793

* Import the yamakaky/rust-bindgen/master branch as `0.19.X` or `classic-bindgen` or something for historical purposes
    * Question: are there any other branches whose history we should preserve?
* Import all tags from yamakaky/rust-bindgen if there are tags we want to preserve
* Finally, @Yamakaky, then you can delete the yamakaky/rust-bindgen repo and fork from this one

**Comment by fitzgen** [comment]
If everyone is on board, I'll start the historical import.

**Comment by emilio** [comment]
@fitzgen: I've already contacted github, and they're making this repo the canonical one.

**Comment by fitzgen** [comment]
Ah ok, great :)

**Comment by emilio** [comment]
It's done, yay! Now we need to manage all the renaming business.

**Comment by Yamakaky** [comment]
Why fork this repo? Can't we just do a redirect from Yamakaky/rust-bindgen to servo/rust-bindgen?

**Comment by fitzgen** [comment]
@Yamakaky so you have somewhere to make pull requests from ;)

**Comment by Yamakaky** [comment]
Right ^^
We also need to do an announcement, since it's a pretty big change.
Also, the header of the README could mention the classic-bindgen branch.

**Comment by Yamakaky** [comment]
Any progress?

**Comment by emilio** [comment]
#414

**Comment by Yamakaky** [comment]
Cool.
