### ISSUE TITLE
Functions implemented in headers leads to link error

### ISSUE THREAD

**Issue by meerik** [servo/rust-bindgen#399]
Ran into a few issues with functions implemented directly in headers in some libraries, took a while to figure out the cause, here is a minimal test case:
You get the same issue with static consts that are just defined in the header and not in the .c-file.

**test.h**
`static inline int myadd(const int x, const int y)
{
	return x + y;
}`

**Bindgen invocation**:
`bindgen.exe --output=output.rs --no-unstable-rust "test.h"  -- -x c -std=c99
`

Resulting **output.rs**:
```
/* automatically generated by rust-bindgen */

extern "C" {
    pub fn myadd(x: ::std::os::raw::c_int, y: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
}

```

Since the function is already implemented in the header, there will be no implementation to link to (i.e corresponding test.c-file). Eventually leading to link error when using the myadd-function.

Expected behavior (one or many of the following):
* Bindgen issues warning during invokation
* Bindgen generates empty function with //TODO-comment + Assert(false) to implement your own implementation
* Bindgen compiles all header-inlined functions into a separate compilation unit and allows linking to them through there (don't know if this would be possible due to preprocessor conditionals)

---------
**clang --version**
```
clang version 3.9.0 (branches/release_39)
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:\Program Files\LLVM\bin
```

**bindgen --version**
`bindgen 0.17.0 `
**Bindgen git hash**
b570ce853e33bfcfa05dd339bf432377c4a2fab8

**Comment by emilio** [comment]
Yeah, you're using a pre-v3.9 libclang, right?

We detect inline functions using libclang 3.9+ and don't generate them. There's no clean way of detecting them with previous versions of libclang (we could try to hack around it looking for the `inline` token, but that feels quite dirty.

This is only a link error if you actually _use_ that function. You can control whether those functions generate symbols with `-fno-inline-functions`, if you have control over the compiled library.

That being said, another more generic solution would be the ideal.

cc #348, which is similar (and has a similar discussion too)

**Comment by meerik** [comment]
Using clang 3.9 (updated issue above).

Actually ýou get the problem even if the function is not marked as inline, the problem comes just by it being implemented in the header file.

**Comment by emilio** [comment]
Sorry, you're completely right. I thought we did that check for everything but apparently we didn't do it for standalone functions, only for methods.

#401 should fix that :)
