### ISSUE TITLE
Document `-blacklist-type SomeType`

### ISSUE THREAD

**Issue by fitzgen** [servo/rust-bindgen#40]
`JS_DefaultLocale` returns `UniqueChars`

Added `-blacklist-type UniqueChars` to rust-mozjs's `etc/bindings.sh`

Regenerated bindings

bindgen is still generating a binding for `JS_DefaultLocale`

**Comment by emilio** [comment]
Oh, that's totally expected, blacklist-type hides the type definition, but there can be things that use it. Can be fixed in #37, but I don't know whether that's worth it.

**Comment by fitzgen** [comment]
Ok then :)
