### ISSUE TITLE
Variadic argument member function failure.

### ISSUE THREAD

**Issue by kkimdev** [servo/rust-bindgen#402]
It happens when the variadic argument function is defined as a class member function.  Then like the below, rust-bindgen tries to generate `...` argument for a non-foreign function, which current rustc doesn't support.

Example:

Header:
```Rust
// In some class
String& AppendWithFormat(const char* formatString, ...);
```

Generated code:
```Rust
// In some impl
    #[inline]
    pub unsafe fn AppendWithFormat(&mut self,
                                   formatString:
                                       *const ::std::os::raw::c_char, ...)
     -> *mut Urho3D_String {
        Urho3D_String_AppendWithFormat(&mut *self, formatString)
    }
```

Compiling the above generated code:
```
error: expected pattern, found `...`
    --> src/generated.rs:1203:71
     |
1203 |                                        *const ::std::os::raw::c_char, ...)
```

I think we should disable code generation for this case and emit a warning for now, unless there is an easy solution for this.

**Comment by kkimdev** [comment]
@luqmana

**Comment by emilio** [comment]
https://github.com/servo/rust-bindgen/pull/403

**Comment by kkimdev** [comment]
Maybe we can keep this issue open for a proper future fix?

**Comment by emilio** [comment]
I think we should open another issue to track that work, I opened https://github.com/servo/rust-bindgen/issues/407
