### ISSUE TITLE
Invalid type identifier generation on `template <typename T> class Foo {     typedef T (FunctionPtr)(); };`

### ISSUE THREAD

**Issue by kkimdev** [servo/rust-bindgen#405]
C++ Header:
```C++
template <typename T>
class Foo
{
  typedef T (FunctionPtr)();
};
```

Generated:
```Rust
pub type Foo_FunctionPtr =
    ::std::option::Option<unsafe extern "C" fn() -> type-parameter-0-0>;
```

Compile error message:
```
error: expected type, found keyword `type`
  --> generated.rs:10:53
   |
10 |     ::std::option::Option<unsafe extern "C" fn() -> type-parameter-0-0>;
```

It should have generated:
```Rust
pub type Foo_FunctionPtr<T> =
    ::std::option::Option<unsafe extern "C" fn() -> T>;
```

Note: the following equivalent C++ header generates correctly now:
```C++
template <typename T>
class Foo
{
  using FunctionPtr = T();
};
```

**Comment by emilio** [comment]
Thanks for the report, we should be able to handle this.

These appear when we start digging too much in clang's AST, but we should be able to detect the `T` before.

Thanks for the report! Will look into it when I have a bit of time (I'm on exams r/n).

**Comment by kkimdev** [comment]
Thanks! I'm trying to use various C++ library in Rust through rust-bindgen and I was surprised by its quality and coverage although I find minor issues along the way.  I impression is that it's not that far from covering vast majority of C++ headers out there.  Great work! :)
