### ISSUE TITLE
bindgen!()

### ISSUE THREAD

**Issue by Yamakaky** [servo/rust-bindgen#416]
The original bindgen crate provides a rust plugin to generate the bindings at compile time. Did you consider adding it?

**Comment by emilio** [comment]
Yeah, it was not maintained and it didn't have any users I know of.

I'll be fine to add it again if someone proposes a use case that can't be addressed via build script, but I think the plugin predates build scripts, so I'm not too fond in rewriting it :)

**Comment by emilio** [comment]
I don't think we want to support it, nobody has complained about its presence so far.

**Comment by Yamakaky** [comment]
^^
