### ISSUE TITLE
rust_enums missing

### ISSUE THREAD

**Issue by jethrogb** [servo/rust-bindgen#430]
I would like my C enums to be defined as individual constants instead of a Rust enum. C enum values can hold any integer which breaks when they're interpreted as Rust enums across FFI boundaries. `bitfield_enum` is not sufficient since this introduces a wrapper type. Using bindgen 0.20 would introduce a public API change for my -sys crates.

**Comment by emilio** [comment]
Again, this should be easy to do, we have options to make some enum variants constant already (see #393), so it'd be a matter of generating that.

**Comment by jethrogb** [comment]
Ah, interesting. I just tried that out a little bit and noticed that returning `EnumVariantCustomBehavior::Constify` for a `bitfield_enum` is broken.

**Comment by emilio** [comment]
Yeah, I can believe so. It doesn't make a lot of sense doing that though (bitfield enums already generate constants), so probably we should just ignore that
