### ISSUE TITLE
Can't convert unions for use with stable Rust

### ISSUE THREAD

**Issue by jethrogb** [servo/rust-bindgen#431]
bindgen 0.19 converted C unions to Rust structs of appropriate size. bindgen 0.20 converts C unions to Rust unions, which I support in general, except that the generated code no longer works on stable Rust. 

Bindgen should support generating stable Rust bindings for all C code.

**Comment by emilio** [comment]
We have this option (see `--no-unstable-rust`), though I agree this should probably be the default.

**Comment by jethrogb** [comment]
Whoops, missed that!
