### ISSUE TITLE
docopt takes forever

### ISSUE THREAD

**Issue by Manishearth** [servo/rust-bindgen#46]
Running bindgen on current m-c takes forever. 

List of arguments: https://gist.github.com/Manishearth/da907aa5efdaaeb84eaf59eab75e172a

In the past, parsing happened almost immediately, but now it's taking more than 5 minutes. Interrupting the program while it runs under a debugger always gives us a backtrace within docopt, behind the `bind_args.iter().decode()` call in bindgen.

cc @fitzgen @BurntSushi

**Comment by emilio** [comment]
This is not funny at all, running that command basically OOMs my (fairly modern) machine while parsing arguments, something is not going well there.

![not-funny](https://cloud.githubusercontent.com/assets/1323194/18118388/48291c8a-6f09-11e6-9506-a4575d7a1ca8.png)

**Comment by Yamakaky** [comment]
5min is not normal. On my bindgen repo, the parsing is also almost instant. I'll try later to remove code on the main to see what's wrong.

**Comment by BurntSushi** [comment]
Definitely a bug somewhere. I'll try to look at it today.

**Comment by emilio** [comment]
Thanks for looking into it @BurntSushi! :-)

**Comment by emilio** [comment]
Docopt was backed out in #37. Let us know if/when it's fixed, though :)

**Comment by Yamakaky** [comment]
Seems good https://github.com/docopt/docopt.rs/issues/195
