### ISSUE TITLE
Test the `is_invalid_named_type` function.

### ISSUE THREAD

**Issue by emilio** [servo/rust-bindgen#460]
In #384 I landed a `is_invalid_named_type` function.

We should add tests to ensure it doesn't mess it up, it'd be helpful to have a few unit tests or doctests for it.

An example of such a test would look like:

```rust
let ty = Type::new(Some("foo".into()), None, TypeKind::Named, false);
assert!(!ty.is_invalid_named_type())
```

**Comment by fitzgen** [comment]
Fixed in cedadf9
