### ISSUE TITLE
stylo's build script crashes inside mangling with "(signal: 11, SIGSEGV: invalid memory reference)" on macOS

### ISSUE THREAD

**Issue by upsuper** [servo/rust-bindgen#462]
See [bug 1335302](https://bugzilla.mozilla.org/show_bug.cgi?id=1335302).

After adding `"--stdlib=libc++", "--target=x86_64-apple-darwin"` to clang args in `build_gecko.rs`, the bindgen does not report any compile error anymore, but it crashes with the stack I pasted in [bug 1335302 comment 3](https://bugzilla.mozilla.org/show_bug.cgi?id=1335302#c3).

I saw #439, and also tested upgrading to clang-sys 0.14.0, but it doesn't seem to help. The build script still crashes at the same location.

It seems to crash when trying to get mangling name of `__find_exactly_one_checked::__matches` at /usr/local/Cellar/llvm/3.9.0/include/c++/v1/tuple:1018:25. But I failed to find minimal reproducible code...

**Comment by upsuper** [comment]
@emilio Could you have a look at this? This is probably not really a bindgen bug... It could be a bug in libclang. I have no idea how can we workaround it.

**Comment by upsuper** [comment]
The issue here is that it somehow doesn't treat `__find_exactly_one_checked` as a template, hence the `cursor.is_in_non_fully_specialized_template()` check returns false and consequently we don't correctly skip mangling `__find_exactly_one_checked::__matches`.

`Cursor::is_template`'s documnet is "Is the referent a template specialization?", which probably shouldn't be named `is_template`. I guess, maybe we should use `is_template_like` or something in `is_in_non_fully_specialized_template`?

**Comment by upsuper** [comment]
Actually this issue is reproducible with the following code:
```c++
template <class... Args>
struct Test {
  static constexpr bool x[] = {Args::x...};
};
```

**Comment by emilio** [comment]
Thanks for the testcase! I'll find a workaround ASAP.

(For the record, Xidorn debugged it and it's a bug in LLVM, I think he submitted a patch?)

**Comment by upsuper** [comment]
It is not necessarily a bug in clang. There is no way in clang itself to hit that condition, and it seems libclang doesn't have no-crashing guarantee for invalid input.

I tried hard to write a test for that issue last night, but failed, so I'm not going to submit a patch for it.
