### ISSUE TITLE
Deduplicate statics

### ISSUE THREAD

**Issue by SimonSapin** [servo/rust-bindgen#47]
Test case:

```cpp
extern int foo;
extern int foo;
```

In the real case where I hit this, the two declarations are in separate files. Still, I believe that multiple identical declarations are legal in C++.

Code generated by bindgen with commit 1e26a8a0ef76656dc3567eb68a954a701fbb42c8:
```rust
extern "C" {
    pub static mut foo: ::std::os::raw::c_int;
    pub static mut foo: ::std::os::raw::c_int;
}
```

Building code like this makes rustc emit an error:

```rust
error[E0428]: a value named `systick_millis_count` has already been defined in this module
    --> src/bindings.rs:3231:5
     |
3207 |     pub static mut systick_millis_count: ::std::os::raw::c_uint;
     |     ------------------------------------------------------------ previous definition of `systick_millis_count` here
...
3231 |     pub static mut systick_millis_count: ::std::os::raw::c_uint;
     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ already defined
```

**Comment by SimonSapin** [comment]
To clarify: only one `static` should be emitted here. Not multiple with a number appended at the end.

**Comment by SimonSapin** [comment]
CC @emilio @nox

**Comment by emilio** [comment]
This should be pretty similar to the pre-existing code in `src/codegen/mod.rs`. See the `functions_seen` member in `CodegenResult`.

**Comment by jeanphilippeD** [comment]
Hello,
I'm very new with rust, but I think I should be able to make a pull request for this following your hint.

**Comment by emilio** [comment]
Hi @jeanphilippeD,

Nice! I'll mark it as assigned to you then.

Let me know if you need any help with this :)
