### ISSUE TITLE
bindgen generates calls to `::std::mem::uninitialized()` when `use_core` is used

### ISSUE THREAD

**Issue by Jascha-N** [servo/rust-bindgen#488]
These should be replaced with calls to `::core::mem::uninitialized()`.

Offending line: https://github.com/servo/rust-bindgen/blob/f5394b34d6140ec5da2e2e5bce0415e1929724bc/src/codegen/mod.rs#L1598. There seem to be a few more hardcoded uses of `::std` in this file.

**Comment by emilio** [comment]
Thanks for reporting this!
