### ISSUE TITLE
Clang version is hardcoded in Cargo.toml

### ISSUE THREAD

**Issue by pornel** [servo/rust-bindgen#496]
I'm getting errors such as 

> function not loaded: clang_Cursor_isAnonymous

because I have clang 3.5 (and unfortunately I can't upgrade it on that machine).

I'm not sure how can I use bindgen with an older version, given that it seems to be hardcoded to use 3.9:

https://github.com/servo/rust-bindgen/blob/8264afa875d686688680123859f8820e19c8028c/Cargo.toml#L42

**Comment by emilio** [comment]
The clang version is not hardcoded. What is hardcoded is the API we use, but we load libclang dynamically, so we do our best. For C I believe libclang 3.6+ would be enough. I'd need to look at the libclang 3.5 docs and see which functions we use can be worked around (for an example of a workaround you can see isFunctionInlined, which we only use if available:

```rust
    pub fn is_inlined_function(&self) -> bool {
        clang_Cursor_isFunctionInlined::is_loaded() &&
        unsafe { clang_Cursor_isFunctionInlined(self.x) != 0 }
    }
```

**Comment by emilio** [comment]
I'm not sure I can compromise myself to support clang 3.5, but I'd be happy to accept patches working around those.

**Comment by emilio** [comment]
Quite curiously, the is_anonymous field is now unused (it was used a while ago) and can be removed, saving that function call.

**Comment by emilio** [comment]
I've opened #497 to fix this specific thing, but I can't promise to get rid of all the codepaths that reach to 3.5+ functions.

**Comment by emilio** [comment]
After that is landed, feel free to report more issues, I'm happy to try to find worarounds as long as they're easy and self-contained enough.

**Comment by pornel** [comment]
It seem like Cursor APIs don't exist in 3.5, and `CompInfo` depends on it heavily, so it may not be possible to run on clang 3.5 at all :(
