### ISSUE TITLE
bindgen crashes in mangling code on windows

### ISSUE THREAD

**Issue by upsuper** [servo/rust-bindgen#502]
It is crashing now... I'll try to find out the reason and update in the issue after other parts of the build finishes.

**Comment by upsuper** [comment]
Code triggers this:
```c++
// bindgen-flags: -- --target=x86_64-pc-win32

template<typename Method, bool Cancelable>
struct nsRunnableMethodTraits;

template<class C, typename R, bool Cancelable, typename... As>
struct nsRunnableMethodTraits<R(C::*)(As...), Cancelable>
{
  static const bool can_cancel = Cancelable;
};
```

It only happens when Windows target is specified, which is probably why other people doesn't meet it even that this is part of m-c code.

**Comment by upsuper** [comment]
But in theory this shouldn't happen, because we should have already exclude templates from generating mangling name... which indicates that the code there is still imperfect.

**Comment by emilio** [comment]
This was fixed.
