### ISSUE TITLE
Generate `PhantomData<UnsafeCell<T>>` to make generic FFI structs lifetime invariant

### ISSUE THREAD

**Issue by fitzgen** [servo/rust-bindgen#506]
Talked with @aturon about this yesterday. This change is needed to make our generated structs invariant, since we can't understand the real variance of the C/C++ things' lifetimes.

**Comment by fitzgen** [comment]
To avoid putting `T: 'static` trait bounds on everything, we should actually generate `PhantomData<UnsafeCell<T>>`, which is the easiest way to get an invariant type without lifetimes AFAIK.

**Comment by fitzgen** [comment]
@Kowasaki, perhaps this is something you'd be interested in?

**Comment by Kowasaki** [comment]
Hello @fitzgen , yes I will take a crack at this!

**Comment by fitzgen** [comment]
I would start by verifying that you can build + run tests. See CONTRIBUTING.md.

The relevant code for this bug is in `src/codegen/mod.rs`. Look for where we generate `CompInfo`'s generic template parameters, if any exist. For each generic template parameter, we should also push a field of type `::$crate::marker::PhantomData<UnsafeCell<$ident>>`.

https://github.com/servo/rust-bindgen/blob/master/src/codegen/mod.rs#L1314

Background for this issue is https://en.wikipedia.org/wiki/Covariance_and_contravariance_(computer_science) and lifetime subtyping in generics.

Let me know if you run into any troubles or have any questions!

**Comment by Kowasaki** [comment]
I've confirmed that I can build and run tests, but I am confused about current_bitfield_layout mentioned in https://github.com/servo/rust-bindgen/blob/master/src/codegen/mod.rs#L1314 . I am not clear on the relationship between the bitfield and the the generic template parameters?

**Comment by fitzgen** [comment]
I should have linked to a specific commit, the line of code just got moved and that comment has nothing to do with this sorry.

Here is where that should have pointed: https://github.com/servo/rust-bindgen/blob/50ee737/src/codegen/mod.rs#L1394

**Comment by Kowasaki** [comment]
Ah I see! So it looks like I should get familiar with the AstBuilder--or at least with the generics?

**Comment by Kowasaki** [comment]
Oh that is helpful. Thanks!

**Comment by Kowasaki** [comment]
Is there a specific test case that I should be using or should I just be making sure that all generated structs be PhantomData<UnsafeCell<T>> instead of  PhantomData<T>?

**Comment by fitzgen** [comment]
> Is there a specific test case that I should be using or should I just be making sure that all generated structs be PhantomData<UnsafeCell<T>> instead of PhantomData<T> ?

We used to generate `PhantomData<T>` if a type parameter wasn't used, but it turned out our is-a-template-parameter-used analysis wasn't smart enough, so I rewrote it as the stuff in `src/ir/named.rs` and stopped generating generic `T` parameters if they aren't used (see the comments at the top of that file if you're curious as to why).

So what you should be looking for is the *new* generation of `PhantomData<UnsafeCell<T>>` for any test case that has a template (and uses the template parameter). There is no longer any *old* `PhantomData<T>` members that are being replaced.

Check out the `tests/headers/template-param-usage-2.hpp` header for a test case that should end up with `PhantomData<UnsafeCell<T>>` after your changes.

Does that make sense? Anything else I can clarify?

**Comment by Kowasaki** [comment]
That makes sense. I think the codebase and its dependencies are a bit more complex than I originally expected so it's taking a bit for me to understand.

**Comment by fitzgen** [comment]
@Kowasaki yeah definitely. I think it helps to take a lazy, call-by-need approach where one only digs as deep into corners of the code base and its dependencies as needed ;)

Here is a sketch of what the changes needed might look like, to help you get on the right track:

```diff
 if let Some(ref params) = used_template_params {
-    for ty in params.iter() {
+    for (idx, ty) in params.iter().enumerate() {
         let param = ctx.resolve_type(*ty);
         let name = param.name().unwrap();
         let ident = ctx.rust_ident(name);
         generics = generics.ty_param_id(ident);

+        let prefix = ctx.trait_prefix();
+        let phantom_ty = quote_ty!(
+            ctx.ext_cx(),
+            ::$prefix::marker::PhantomData<::$prefix::cell::UnsafeCell<$ident>>);
+        let phantom_field = StructFieldBuilder::named(format!("_phantom_{}", idx))
+            .build_ty(phantom_ty);
+        fields.push(phantom_field);
     }
 }
```

**Comment by fitzgen** [comment]
@Kowasaki hi! How are things going? Are you still working on this? Any more questions I can help answer or anything I can do to help?

**Comment by Kowasaki** [comment]
Hey, sorry for the lack of responses! I am still working on this and have been stuck trying to figure out how to write a test case that can cause `PhantomData<UnsafeCell<T>>` to not be generated for an used template parameter. It seems like the snippet above have basically done the requirement based on the included tests so I am unsure as to what else should be done?

**Comment by fitzgen** [comment]
@Kowasaki great to hear you're still working on this :)

This change shouldn't need any new tests -- the existing test suite should have multiple test expectations that will get updates from this patch. For example, at least some of the template parameter usage test expectations should have `PhantomData` members after this patch, when they did not have a `PhantomData` before. Have you seen any of these new `PhantomData` members in the test expectations?

Perhaps it would be useful to open a WIP pull request so we can speak concretely about specific tests and lines of code?

**Comment by Kowasaki** [comment]
My apologies for the delay--I've submitted the pull along with the test expectations, which show all the new `PhantomData ` members.
