### ISSUE TITLE
Make 'cargo test' work

### ISSUE THREAD

**Issue by SimonSapin** [servo/rust-bindgen#51]
At least some of the reason is that 9f78ea9c83b04dbf1b4ee5c11882ab5c878f7f90 did not update test expectations.

Once this is fixed, `cargo test` should be added to `.travis.yml`.

**Comment by emilio** [comment]
`cargo test` is not expected to work, nor be up to date. It was a churn to add new tests and modify expectations, so I added the `make test` command.

Agreed that should be better to use a rust harness though.

**Comment by SimonSapin** [comment]
Then maybe remove the tests that are not expected to pass? They’ll be in the git history when it’s time to bring them back.

**Comment by fitzgen** [comment]
I think we need a better story than we currently have for running tests, if only for potential contributors and newcomers to this code base.

Right now, I run `make test` and get no message about whether the test suite overall passed or had failures. I can't even rely on `$?`. If I look into `.travis.yml`, I'll find that finding out if my test run passed effectively relies on git diff'ing the `test/expectations` directory. But I can't even do `make test` on master without getting diffs in that directory!

This is not friendly for contributors. We need a much better story here.
