### ISSUE TITLE
inexplicable errors trying to bind FAST

### ISSUE THREAD

**Issue by mattmacy** [servo/rust-bindgen#514]
I have a simple builder in the following project.
https://github.com/mattmacy/ruFAST

for starters I'm just generating wrappers for the following two headers:
#include <FAST/Importers/ImageFileImporter.hpp>
#include <FAST/Algorithms/ImageResampler/ImageResampler.hpp>

These include a tremendous amount of stuff including Eigen/Dense which seems to cause an awful lot of build errors.
See the following gist:
https://gist.github.com/mattmacy/07de40bb41b49672f442df3cfd3fcb7f

To reproduce just build / install the following and either libeigen3-dev or libeigen2-dev.
https://github.com/smistad/FAST

**Comment by mattmacy** [comment]
If I just include Eigen/Core (FAST includes Eigen/Dense which in turn include Eigen/Core) I get fewer errors:
http://pasted.co/286422b0

diff --git a/src/wrapper.hpp b/src/wrapper.hpp
index 2b037e7..5b538ba 100644
--- a/src/wrapper.hpp
+++ b/src/wrapper.hpp
@@ -1,2 +1,3 @@
-#include <FAST/Importers/ImageFileImporter.hpp>
-#include <FAST/Algorithms/ImageResampler/ImageResampler.hpp>
+#include <Eigen/Core>
+//#include <FAST/Importers/ImageFileImporter.hpp>
+//#include <FAST/Algorithms/ImageResampler/ImageResampler.hpp>

**Comment by mattmacy** [comment]
It doesn't look like bindgen properly mangles struct scoped typedefs.

The apt packages that llvm supposedly builds for Ubuntu / Debian don't actually so I used the pre-built binaries and put them in ~/.bin/llvm-3.9 char_type appears to be repeatedly redefined in different contexts and scoped to individual structs, e.g. include/c++/v1/string:504:
// char_traits

template <class _CharT>
struct _LIBCPP_TYPE_VIS_ONLY char_traits
{
    typedef _CharT    char_type;

627:
// char_traits<char>

template <>
struct _LIBCPP_TYPE_VIS_ONLY char_traits<char>
{
    typedef char      char_type;

717:
#ifndef _LIBCPP_HAS_NO_UNICODE_CHARS

template <>
struct _LIBCPP_TYPE_VIS_ONLY char_traits<char16_t>
{
    typedef char16_t       char_type;

etc. etc.

find ~/.bin/llvm-3.9 -type f | xargs grep "char_type;" | grep typedef    
/home/mmacy/.bin/llvm-3.9/include/c++/v1/ios:    typedef charT char_type;
/home/mmacy/.bin/llvm-3.9/include/c++/v1/ios:    typedef _CharT char_type;
/home/mmacy/.bin/llvm-3.9/include/c++/v1/streambuf:    typedef charT char_type;
<...>
/home/mmacy/.bin/llvm-3.9/include/c++/v1/string:    typedef charT     char_type;
/home/mmacy/.bin/llvm-3.9/include/c++/v1/string:    typedef _CharT    char_type;
/home/mmacy/.bin/llvm-3.9/include/c++/v1/string:    typedef char      char_type;
/home/mmacy/.bin/llvm-3.9/include/c++/v1/string:    typedef wchar_t   char_type;
/home/mmacy/.bin/llvm-3.9/include/c++/v1/string:    typedef char16_t       char_type;
/home/mmacy/.bin/llvm-3.9/include/c++/v1/string:    typedef char32_t       char_type;
/home/mmacy/.bin/llvm-3.9/include/c++/v1/string:    typedef typename _Traits::char_type char_type;
/home/mmacy/.bin/llvm-3.9/include/c++/v1/__locale:    typedef _CharT char_type;
/home/mmacy/.bin/llvm-3.9/include/c++/v1/__locale:    typedef char char_type;
/home/mmacy/.bin/llvm-3.9/include/c++/v1/__locale:    typedef wchar_t char_type;
/home/mmacy/.bin/llvm-3.9/include/c++/v1/__locale:    typedef wchar_t char_type;
/home/mmacy/.bin/llvm-3.9/include/c++/v1/__locale:    typedef char char_type;
/home/mmacy/.bin/llvm-3.9/include/c++/v1/__locale:    typedef char char_type;
/home/mmacy/.bin/llvm-3.9/include/c++/v1/__locale:    typedef wchar_t char_type;
/home/mmacy/.bin/llvm-3.9/include/c++/v1/__locale:    typedef char char_type;
/home/mmacy/.bin/llvm-3.9/include/c++/v1/__locale:    typedef wchar_t char_type;

**Comment by emilio** [comment]
Well, I wouldn't call these "inexplicable". C++ is a complex language, and overall when complex templates come into place, bindgen can't understand absolutely everything.

The way to go when doing bindings to C++ is using the whitelisting APIs to generate what you need. If you need one of the things bindgen can't generate correct code for, the way to go is using the blacklisting APIs, and add custom replacements for those.

**Comment by mattmacy** [comment]
I missed the "have to" whitelist bit. I'd have to disable recursive white listing because it uses strings, so easier to just write a C wrapper lib for the bits I need and bind that. Thanks.
