### ISSUE TITLE
Bindgen generates unnecessary padding inside nsIDocument on Windows

### ISSUE THREAD

**Issue by upsuper** [servo/rust-bindgen#520]
On my machine, the generated `nsIDocument` is like this:
```rust
    #[repr(C)]
    #[derive(Debug)]
    pub struct nsIDocument {
        pub _base: root::nsINode,
        pub _base_1: root::mozilla::dom::DispatcherTrait,
        pub mDeprecationWarnedAbout: u64,
        pub mDocWarningWarnedAbout: u32,
        pub mSelectorCache: root::nsIDocument_SelectorCache,
        pub __bindgen_padding_0: [u64; 10usize],
        pub mReferrer: root::nsCString,
        pub mLastModified: ::nsstring::nsStringRepr,
        // ...
    }
```

I see no reason why there needs to be a 80byte padding.

This causes a mismatch between offset from C++ and from Rust (`mReferrer`'s offset is 248 in C++ but 328 in Rust), which leads to servo/servo#15483 on Windows.

It seems that this doesn't happen on Mac or Linux, so `--target=x86_64-pc-win32` is probably a necessary condition.

**Comment by emilio** [comment]
That is fixed in #512, and in https://github.com/servo/servo/pull/15216. That was why the bindgenup has been blocked for so long. Sorry about that.

**Comment by emilio** [comment]
This was not windows specific, it was a regression from #468, that isn't yet in the rest of platforms (I believe you updated your bindgen checkout in msvc, right?).

**Comment by upsuper** [comment]
Oh, the same issue? Great... so probably I'm seeing this because I'm using a more recent version of bindgen for the crash.

**Comment by upsuper** [comment]
Let me try the latest master with your patch in #512.

**Comment by emilio** [comment]
This should be fixed on master now, feel free to reopen if the problem persists (though I hope not! :P).
