### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by pornel** [servo/rust-bindgen#522]
Could you publish the latest bindgen to crates.io? 

The recent fixes for older clang would help me a lot deploying Rust without need to replace packages.

**Comment by fitzgen** [comment]
Sure thing, give me a minute.

**Comment by fitzgen** [comment]
Looks like @emilio beat me to it :)

0.22.0 is on crates.io!

**Comment by fitzgen** [comment]
(Also, @emilio we need to remember to tag releases, since it helps people determine new changes, and also helps us figure out whether new releases need to be breaking changes or not -- thanks!)

**Comment by fitzgen** [comment]
Hrm... I can't seem to push tags to servo/rust-bindgen anymore :-/ Not sure what is going on.

**Comment by emilio** [comment]
On Fri, Feb 17, 2017 at 07:47:10AM -0800, Nick Fitzgerald wrote:
> (Also, @emilio we need to remember to tag releases, since it helps
> people determine new changes, and also helps us figure out whether new
> releases need to be breaking changes or not -- thanks!)

Whoops, fwiw I _did_ remember to tag when publishing, just pushed to my
own repo instead of upstream, sorry! Just did now.

**Comment by pornel** [comment]
Hi! Could you make another release?

**Comment by emilio** [comment]
Done! :)
