### ISSUE TITLE
Fix the CI + OSX situation...

### ISSUE THREAD

**Issue by fitzgen** [servo/rust-bindgen#526]
TODO

* [ ] feature gate obj-c support
* [ ] test that obj-c builds under linux, but don't run obj-c related tests (as they require an OSX machine)
* [x] stop running OSX builds on travis CI

**Comment by emilio** [comment]
We could just run tests with `--target <osx>` I think, assuming we fix #593.

**Comment by fitzgen** [comment]
Actually I think we can close this. We're already running obj-c expectation tests via cross compiling from linux. No plans to actually run the layout tests on OSX because Travis CI is too slow.
