### ISSUE TITLE
Generate code that not produce style warnings

### ISSUE THREAD

**Issue by Dushistov** [servo/rust-bindgen#540]
After invoking bindgen (0.22) against "jni.h", "android/log.h", "android/bitmap.h" I got bunch of warnings,
like:

> warning: constant `__llvm__` should have an upper case name such as `__LLVM`, #[warn(non_upper_case_globals)] on by default
>   --> src/android_c_headers.rs:27:1
>    |
> 27 | pub const __llvm__: ::std::os::raw::c_uint = 1;
>    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> warning: constant `__UINT_FAST32_FMTo__` should have an upper case name such as `__UINT_FAST32_FMTO`, #[warn(non_upper_case_globals)] on by default
>    --> src/android_c_headers.rs:229:1
>     |
> 229 | pub const __UINT_FAST32_FMTo__: &'static [u8; 2usize] = b"o\x00";
>     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> warning: constant item is never used: `unix`, #[warn(dead_code)] on by default
>    --> src/android_c_headers.rs:277:1
>     |
> 277 | pub const unix: ::std::os::raw::c_uint = 1;
>     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 

and so on, I migrate from Yamakaky/rust-bindgen, which doesn't produce such warnings,
it generate code with warnig suppression,
can it be done in your variant of bindgen in similar way?

**Comment by emilio** [comment]
Sure you can. You can use `--raw-line` to add the warning suppression yourself, or if you're using a build script an including it you can do something like:

```
#[allow(non_upper_case_globals, dead_code)]
pub mod bindings {
    include!(..)
}
```

**Comment by Dushistov** [comment]
@emilio 
>Sure you can

Actually no I can not, thanks for `raw_line` point,
I tried this:

```
    let mut bindings: ::bindgen::Builder = bindgen::builder().header(c_file_path.to_str().unwrap());
    bindings = include_dirs.iter().fold(bindings, |acc, x| acc.clang_arg("-I".to_string() + x.to_str().unwrap()));

    bindings = bindings
        .no_unstable_rust()
        .raw_line("#[allow(non_upper_case_globals)]")
        ;
    bindings = try!(c_headers[1..].iter().fold(Ok(bindings), |acc: Result<::bindgen::Builder, String>, header| {
        let c_file_path = try!(search_file_in_directory(include_dirs, header)
                               .map_err(|_| format!("Can not find {}", header)));
        let c_file_str = try!(c_file_path.to_str()
                              .ok_or_else(|| format!("Invalid unicode in path to {}", header)));
        Ok(acc.unwrap().clang_arg("-include").clang_arg(c_file_str))
    }));
    
    let generated_bindings = try!(bindings.generate().map_err(|_| "Failed to generate bindings".to_string()));
    try!(generated_bindings.write_to_file(output_rust).map_err(|err| err.to_string()));

```

but no `#[allow(non_upper_case_globals)]` at the begining of file :(

**Comment by emilio** [comment]
Hmm... Are you sure what happens isn't that you need `#![allow(non_upper_case_globals)]` instead? What version of bindgen are you using?

**Comment by Dushistov** [comment]
>Are you sure what happens isn't that you need #![allow(non_upper_case_globals)]

I suppose this is not important, because of I just have no such string at the beginning of
generated file. If will have one, I suppose, I quickly  find proper `allow` magic.

>What version of bindgen are you using?

As I mentioned in the first message, I use "0.22.0" and buildscript.

**Comment by Dushistov** [comment]
Looks like some caching issue, now my lines appear in generated file after call `raw_line`

**Comment by emilio** [comment]
Ok, glad to hear it! :)
