### ISSUE TITLE
The rustfmt CI assertions are broken

### ISSUE THREAD

**Issue by fitzgen** [servo/rust-bindgen#546]
and CI is not asserting that things are `rustfmt`ed properly.

We need to add

```
export PATH=$PATH:~/.cargo/bin
```

after installing `rustfmt`, but there is a bug in `rustfmt` that will prevent this assertion from ever passing right now: https://github.com/rust-lang-nursery/rustfmt/issues/1344

Note that the script is just letting everything through right now, so we don't need to change our CI script until after that rustfmt bug is fixed.

**Comment by emilio** [comment]
They're no longer broken, but they were disabled IIRC, because they were slightly annoying... I'm all in for consistent coding-style, but just a new rustfmt version shouldn't make our CI turn red.

I'm closing this, let's re-enable them if you want.
