### ISSUE TITLE
Filtering out builtins from --emit-clang-ast only half-works

### ISSUE THREAD

**Issue by fitzgen** [servo/rust-bindgen#571]
#566 only fixed half the situation it seems. When I run with `--emit-clang-ast`, the builtin types are only half-filtered:

```
(

 type.kind = Invalid
)
(

 type.kind = Invalid
)
(

 type.kind = Invalid
)
(

 type.kind = Invalid
)
(

 type.kind = Invalid
)
(

 type.kind = Invalid
)
(

 type.kind = Invalid
)
```

Etc...

We should finish the job and not even print those shells out. @tsliang, want to finish this?

**Comment by fitzgen** [comment]
I think the check needs to be earlier.

**Comment by tsliang** [comment]
@fitzgen can do! It seems that the easiest thing to do would be to simply move the short-circuit in `print_type` (line 1559:1561) above the call to `print_indent` (line 1558). Alternatively, could we move both of these checks to `ast_dump` itself? There's no way that a builtin would have children that would need to be dumped, right?

**Comment by fitzgen** [comment]
> Alternatively, could we move both of these checks to ast_dump itself?

This sounds pretty good to me. The only concern is that if someone explicitly calls `ast_dump(some_builtin, 0)` then they *should* get the dump for it.

One sorta hacky way to do this would be to check the indent level and whether it is zero or not. The other way would be to make `ast_dump` always dump the builtins and filter the builtins before we call `ast_dump` in the `parse` function in `src/lib.rs`:

```rust
    if context.options().emit_ast {
        cursor.visit(|cur| clang::ast_dump(&cur, 0)); // <---- add filtering here
    }
```

I like the latter idea.

> There's no way that a builtin would have children that would need to be dumped, right?

Not AFAIK
