### ISSUE TITLE
Bindgen panics in Stylo on master

### ISSUE THREAD

**Issue by fitzgen** [servo/rust-bindgen#584]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1336013

```
 0:17.10 thread '<unnamed>' panicked at 'C'mon: Continue', C:\bot\slave\stable-dist-rustc-win-msvc-64\build\src\libcore\result.rs:837
...
 0:17.10    7:     0x7ff63f888a2f - core::result::unwrap_failed<bindgen::parse::ParseError>
 0:17.10                         at C:\bot\slave\stable-dist-rustc-win-msvc-64\build\src\libcore\macros.rs:29
 0:17.10    8:     0x7ff63f8d46d0 - bindgen::ir::ty::Type::from_clang_ty
 0:17.10                         at S:\blue\third_party\rust\bindgen\src\ir\ty.rs:1024
...
0:17.11 thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any', C:\bot\slave\stable-dist-rustc-win-msvc-64\build\src\libcore\result.rs:837
```

There's a couple places where I think we should stop asserting that we can always generate an IR item, and instead fall back to generating opaque items when we inevitably fail on something.

**Comment by upsuper** [comment]
I've had a patch to fix this.

**Comment by emilio** [comment]
This wasn't completely fixed by that commit AFAIK.

**Comment by fitzgen** [comment]
Making this issue about getting Stylo working with master bindgen again. The libclang 4.0 stuff is tracked in https://github.com/servo/rust-bindgen/issues/585

**Comment by fitzgen** [comment]
After much patience, `creduce` gives us this reduction of the panic I was getting when generating bindings for stylo with master bindgen:

```c++
template <class> class RefPtr;
class b;
class A {
  typedef b a;
};
template <class c> class e { RefPtr<c> d; };
template <class> class f {};
class g {
  f<e<int>> h;
};
class b : g {};
A Servo_Element_GetSnapshot();
```

**Comment by fitzgen** [comment]
Ok, this is an interaction between blacklisting and the template analysis.
