### ISSUE TITLE
Determine if simple constants defined in header files exist at build time

### ISSUE THREAD

**Issue by ambaxter** [servo/rust-bindgen#590]
For https://github.com/openSUSE/libsolv

I need the capability to determine if simple constants are defined at build time. In libsolv's case, this tells me which headers are valid for the ext library.

### Input C/C++ Header
#ifndef LIBSOLV_SOLVVERSION_H
#define LIBSOLV_SOLVVERSION_H
<snip>

#define ENABLE_RPMPKG
#define ENABLE_PUBKEY
/* #undef LIBSOLVEXT_FEATURE_BZIP2_COMPRESSION */

<snip>
#endif

### Bindgen Invokation

 Perhaps something like this?

```Rust
bindgen::Builder::default()
    .header("input.h")
    .ifdef("ENABLE_RPMPKG").<some function or additional action>
    .generate()
    .unwrap()
```

**Comment by emilio** [comment]
I was thinking of something a bit easier (from the bindgen implementation's point of view).

See, for example, the `TypeChooser` trait (in `src/chooser.rs`, which allows choosing integer types for macro variants).

I was thinking of something similar, mainly, giving bindgen a trait object, and invoking a method on it each time `X` happens.

You could do something really similar to it (maybe the name does not belong to `TypeChooser`, any better name welcome), but with something like `parsed_foo`.

For example:

```rust
trait BindgenVisitor {
     fn parsed_macro(&self, name: &str) {}
}
```

(And then override it with your custom method).

But now that you mention the exact flag you're looking for, I'm not sure that's going to be enough for that library, given it seems to be gone after build time (so bindgen will never see it).

Perhaps you can use it with [`RPM_COOKIE_VERSION`](https://github.com/openSUSE/libsolv/blob/3edcaace14c71804ac571068276fe81880880478/ext/repo_rpmdb.c#L63) or something like that, but then you need to include unconditionally the extension header, which I guess defeates the purpose of what you're trying to do :(.

**Comment by ambaxter** [comment]
The header file that sets the defines in question gets installed with the library so it shouldn't be gone after build time.

**Comment by emilio** [comment]
Oh, I see, then what I commented above should apply (I'm surprised a library exports such generic macro names TBH, but fine).

I guess the question is how the API would look like. I'm tempted to just rename `TypeChooser` to something more generic and stick this API there, but another API could be ok as long as the name is relevant. WDYT @fitzgen?

In any case, `TypeChooser` should be a really decent reference of how to implement this, and the hooks must be called in `src/ir/var.rs`, each time you parse a macro.

**Comment by ambaxter** [comment]
Wouldn't renaming TypeChooser break the existing API?

**Comment by emilio** [comment]
Right, but we've done breaking changes already that we need to publish, so rolling a rename into this wouldn't hurt.

**Comment by ambaxter** [comment]
I did some testing. It looks like cexpr doesn't parse the simple #define entries. I'll look at this more later.

**Comment by emilio** [comment]
Sure, I don't expect cexpr to deal with empty macros, but you should have access to `cursor.spelling()` in the line before the call to `parse_macro`.

**Comment by ambaxter** [comment]
Closed with https://github.com/servo/rust-bindgen/pull/591
