### ISSUE TITLE
Generate type ids lazily

### ISSUE THREAD

**Issue by bholley** [servo/rust-bindgen#60]
This will prevent small changes from creating large diffs in the bindings. Emilio says it will also improve the tests.

**Comment by bholley** [comment]
CC @emilio

**Comment by emilio** [comment]
For the record, this proposal is something like generating *on top* of the current `ItemId` another id, like `generated_item_id`, that would depend only on the amount of items that have been generated, and thus would be more deterministic than the current approach, that depends on the number of items parsed.

This would allow to include system headers in tests.
