### ISSUE TITLE
Detect forward declarations and generate opaque enums for them.

### ISSUE THREAD

**Issue by emilio** [servo/rust-bindgen#62]
We should be able to detect forward declarations in bindgen, and generate opaque enums if appropriate, instead of structs with an address byte.

We should check `clang_getCursorDefinition()` and `clang_isCursorDefinition` to check whether what we're scanning, mark the generated type accordingly, and do the proper codegen steps.

**Comment by fitzgen** [comment]
#198 is a dupe of this issue, but for posterity it does include an example with a bit more detail than we have in this issue.

**Comment by cynicaldevil** [comment]
I'll try this one.

**Comment by emilio** [comment]
Great, let us know if you need anything :)
