### ISSUE TITLE
MacPorts Clang 3.9 Instructions

### ISSUE THREAD

**Issue by casey** [servo/rust-bindgen#64]
I use MacPorts on OS X, and was able to build bindgen. You might want to consider adding instructions to the readme:

1. To install clang:
  `port install clang-3.9`

2. And to build rust-bindgen:
```
LIBCLANG_PATH=/opt/local/libexec/llvm-3.9/lib \
LD_LIBRARY_PATH=/opt/local/libexec/llvm-3.9/lib \
cargo build
```

**Comment by emilio** [comment]
Thanks! I added it in #65 :)

**Comment by casey** [comment]
Awesome :) You're welcome!
