### ISSUE TITLE
feature request: convert snake_case types to CamelCase

### ISSUE THREAD

**Issue by mikeyhew** [servo/rust-bindgen#647]
I'm trying to use bindgen to create bindings for ruby. I'm getting an error because ruby.h defines `rb_global_variable` twice, once as a `struct`, and once as a function.

As far as I understand, the names of `structs`, `enums`, and `unions` don't have to match up between C and Rust - only function names do. In light of that, would it be possible add an option to rename `struct` and other type names to camel case? In general, it would be also be cool if we could rename types arbitrarily, by providing a function or a list of names to rename. For example, `rb_global_variable` could become `GlobalVariable`.

**Comment by emilio** [comment]
Hmm... So that's one of the slightly annoying differences between C and C++ that pisses me off the most.

Doesn't seem too hard to add a hook for renaming some things while we're parsing. We already have a few `ParseCallbacks` for customizing enum behavior and similar stuff.

**Comment by emilio** [comment]
Would you be interested in giving this a try? In particular, it'd be a matter of adding a new method to `ParseCallbacks`, and hooking it here: https://github.com/servo/rust-bindgen/blob/master/src/ir/ty.rs#L1242

**Comment by mikeyhew** [comment]
Sure - I have a few things I want to get done first, but I can take a crack at it sometime in the next week or so.

**Comment by emilio** [comment]
I wonder if #654 helps here?

**Comment by emilio** [comment]
(Not with the feature, but with the problem it's trying to solve)

**Comment by mikeyhew** [comment]
Ya, it would. It's the same problem that I am having.

**Comment by emilio** [comment]
Can you try with bindgen 0.24 and report back? I can try to add more customization if needed, but if it's fixed, that'd be rad :)

**Comment by mikeyhew** [comment]
I checked, and yes, it works :) see https://github.com/mikeyhew/ruby-sys/tree/bindgen

**Comment by emilio** [comment]
Awesome, thanks for checking!

**Comment by RReverser** [comment]
@emilio My understanding is that the issue that @mikeyhew had is solved, but this particular feature request is still valid / not implemented, so perhaps should stay open?

**Comment by emilio** [comment]
Yeah, fair :).

I opened #785 to track that instead of reopening this one.
