### ISSUE TITLE
Add in-worklist bits to the analysis runner

### ISSUE THREAD

**Issue by fitzgen** [servo/rust-bindgen#664]
RIght now, we might put the same item in the worklist many times over. This leads to inefficient re-computations that end up having no effect.

We could add a bitset to the analysis runner that maps `ItemId` to a boolean that is `true` if the item with the given id is currently in the worklist. Then, when enqueuing new work, we would avoid pushing duplicates onto the worklist if the bit is set for the about-to-be-enqueued item. After popping an item from the worklist, we would unset the bit. The changes would be completely within this function (except maybe adding a dependency to Cargo.toml for a bitset collection): https://github.com/servo/rust-bindgen/blob/316b1a9/src/ir/named.rs#L195-L210

We would want to make sure that this optimization is carrying its weight by timing how long Stylo bindings take to generate before and after this change: https://github.com/servo/rust-bindgen/blob/aaaa08a/tests/stylo_sanity.rs#L546 I would be very surprised if this didn't pay for itself, however.

I am happy to mentor someone who has some prior experience with Rust or bindgen on this change.

**Comment by tmfink** [comment]
@fitzgen I implemented the optimization you described in a feature branch. However, I am not observing a speedup in the Stylo sanity test. There's enough variance that the sometimes my "optimized" version is slower.

https://github.com/tmfink/rust-bindgen/tree/feature-664-worklist-bitset

Below are representative results for both the original and my "optimized" version:
~~~
$ cargo test sanity_check_can_generate_stylo_bindings --release
...
Generated Stylo bindings in: Duration { secs: 3, nanos: 752511048 }
...
~~~

Is my code wrong? Does anyone else observe a speedup?

**Comment by fitzgen** [comment]
@tmfink thanks for digging in! :)

Would you mind making a work-in-progress PR? Its a lot easier to talk about the code in a place where we can comment on individual lines and such things.

Regarding speed, did you attempt measuring just the analysis phase's time? I suspect that most of our time in bindgen is generally spent in libclang's parsing and type checking, but I haven't done very much profiling because it honestly hasn't been too much of an issue yet.

**Comment by tmfink** [comment]
Created pull request https://github.com/servo/rust-bindgen/pull/705

**Comment by fitzgen** [comment]
See https://github.com/servo/rust-bindgen/pull/705#issuecomment-302503717
