### ISSUE TITLE
Support GCC's `short-enums` flag

### ISSUE THREAD

**Issue by jamesmunns** [servo/rust-bindgen#711]
Hello, GCC has a flag called `short-enums`, which will dynamically size the representation of the enumeration based on its contents.

This C code would compile (and pass static asserts) with `-fshort-enums` enabled:

```c
typedef enum {
    SOME_VALUE = 0x1,
} one_byte_t;

static_assert(sizeof(one_byte_t) == 1);

typedef enum {
    SOME_OTHER_VALUE = 0x100,
} two_byte_t;

static_assert(sizeof(two_byte_t) == 2);

typedef enum {
    SOME_BIGGER_VALUE = 0x1000000,
} four_byte_t;

static_assert(sizeof(four_byte_t) == 4);

```

Currently bindgen will generate all of these enumerations as the size of `int`, which is `u32` on my platform. This breaks the structure of `struct`s when trying to interface with C code from Rust due to alignment issues. Additional information is available here: http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dui0774b/chr1411640303038.html

This flag is somewhat widely used on microcontrollers in an attempt to save memory.

**Comment by emilio** [comment]
(As discussed on IRC, passing that flag down to clang should be enough, I'll land a test case to ensure we don't regress it)

**Comment by jamesmunns** [comment]
I can confirm this worked for me! In case someone finds this later, adding this to my build invocation fixed this:

```rust
    let bindings = Builder::default()
        .header("bindings.h")
        .clang_arg("-DSOMETHING")

        .clang_arg("-fshort-enums") // This is the magic!

        .clang_arg(env::var("TARGET").unwrap())
        .generate()
        .expect("Unable to generate bindings");
```
