### ISSUE TITLE
PhantomData is sometimes unnecessary for generic types

### ISSUE THREAD

**Issue by upsuper** [servo/rust-bindgen#715]
### Input C/C++ Header

```C++
template<typename T> class Test { T* ptr; };
```

### Bindgen Invocation

```
$ bindgen input.h
```

### Actual Results

```rust
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Test<T> {
    pub ptr: *mut T,
    pub _phantom_0: ::std::marker::PhantomData<::std::cell::UnsafeCell<T>>,
}
```

### Expected Results

In this example, the `_phantom_0` is unnecessary. It can just generate
```rust
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Test<T> {
    pub ptr: *mut T,
}
```

**Comment by emilio** [comment]
This is known, and it's intended, see #689. Basically, it allows getting the subtyping semantics that are expected (AFAIK).

@fitzgen or @aturon can probably elaborate on this.
