### ISSUE TITLE
Generate properly mangled test names

### ISSUE THREAD

**Issue by Manishearth** [servo/rust-bindgen#723]
Currently bindgen generates a lot of tests like so:

```rust
    #[test]
    fn __bindgen_test_layout_nsTArray_instantiation_34() {
        assert_eq!(::std::mem::size_of::<root::nsTArray<root::nsCString>>() ,
                   8usize , concat ! (
                   "Size of template specialization: " , stringify ! (
                   root::nsTArray<root::nsCString> ) ));
        assert_eq!(::std::mem::align_of::<root::nsTArray<root::nsCString>>() ,
                   8usize , concat ! (
                   "Alignment of template specialization: " , stringify ! (
                   root::nsTArray<root::nsCString> ) ));
    }
```

The number is there because there is such a test for each `T` that is used as `nsTArray<T>`. Furthermore, the counting is global -- adding another instantiation will renumber _all_ such tests, not just the array ones. This means that nontrivial binding updates are very prone to bitrot.

Instead of numbering this we should do something like `fn __bindgen_test_layout_nsTArray_lt_nsCString_gt_instantiation`. Basically, some mangling scheme that can reliably produce unique names.

cc @emilio

**Comment by fitzgen** [comment]
Was this fixed in https://github.com/servo/rust-bindgen/pull/829 ? @Manishearth @emilio

**Comment by Manishearth** [comment]
Lol yeah looks like I filed this is twice
