### ISSUE TITLE
C++ classes using STL types internally

### ISSUE THREAD

**Issue by michael-p** [servo/rust-bindgen#725]
Note: this is not really a bug in bindgen but more of a question about how to do this sort of thing (if possible at all).

### Input C/C++ Header
```C++
#include <string>

class Test {
private:
    std::string m_value;
public:
    Test();
    const char* get_value();
};
```

### Bindgen Invocation
```Rust
bindgen::Builder::default()
        .no_unstable_rust()
        .header("test.hpp")
        .whitelist_recursively(false)
        .whitelisted_type("Test")
        .layout_tests(true)
        .clang_arg("-x")
        .clang_arg("c++")
        .clang_arg("-std=c++11")
        .generate()
        .expect("error when generating bindings")
        .write_to_file(out_dir.join("bindings.rs"))
        .expect("error when writing bindings");
```

### Actual Results
Generated code fails to compile:
```
error[E0412]: cannot find type `std_string` in this scope
 --> /Users/michaelp/Documents/rust/bindgen_test/target/debug/build/bindgen_test-fc9b27fe4ab64bfd/out/bindings.rs:5:18
  |
5 |     pub m_value: std_string,
  |                  ^^^^^^^^^^ not found in this scope
```

If I allow bindgen to pull `std::string` in by removing `.whitelist_recursively(false)` above I get tons of other compile errors about types deep in the C++ STL (which, I guess, is kind of expected).

### Expected Results
Is there a way to do this at all? I.e. generate code for classes that uses STL types like `std::string` or `std::vector` internally (as private data members)? I understand that having those types in the public interface is very unlikely to work but as a private data member?
Moreover, if I do have a class that uses, say, `std::string` as a parameter to a public member function, is there a way to still generate code for that class? Even if that would for example mean ignoring that specific method?

Thank you for your help!
Michael

**Comment by michael-p** [comment]
Ok figured it out, one has to treat the class itself as opaque by calling `.opaque_type("Test")` above.
Sorry for the issue-spam! :)

**Comment by emilio** [comment]
Glad you figured it out!

For the record, marking as opaque_type("std::string") should work
equally well, and perhaps it's a bit cleaner.

Cheers :)
