### ISSUE TITLE
Switch defaults from generating unstable Rust to generating stable Rust

### ISSUE THREAD

**Issue by fitzgen** [servo/rust-bindgen#757]
The current default is definitely the wrong choice.

This involves 

* changing the `Builder::no_unstable_rust` method to the `Builder::unstable_rust` method

* changing the `--no-unstable-rust` flag to a `--unstable-rust` flag in `src/options.rs`

* I don't think this will require updating test results since we run all the tests with `--no-unstable-rust`, however it may require removing that flag from the test harness. I sugget `git grep`ing for "unstable" to see places in the code base that may require updating.

**Comment by jonstites** [comment]
I'll take a stab at this one. @highfive: assign me

**Comment by rigelk** [comment]
@jonstites sorry, had this done already :/
