### ISSUE TITLE
Rewrite `can_derive_debug` as either a graph traversal or fix-point analysis

### ISSUE THREAD

**Issue by fitzgen** [servo/rust-bindgen#767]
See https://github.com/servo/rust-bindgen/issues/536 for details.

**Comment by photoszzt** [comment]
While I'm waiting things to compile, I wrote part of this following the skeleton in #765 in https://github.com/photoszzt/rust-bindgen/commit/9e170ae5c716bfb77d120777cc55ef5ce6d6f5ed. I also separate the MonotoFramework to the other file (https://github.com/photoszzt/rust-bindgen/commit/718d367b805a10cb02634a25cf0911eeb175a0d8). 

Looking at the skeleton code, I'm not sure where the consider_edge is used.

**Comment by fitzgen** [comment]
@highfive assign @photoszzt

**Comment by fitzgen** [comment]
Hmm, I guess highfive bot doesn't let you assign other people, and I can't assign either. Ah well.

Anyways, cool! :)

The commit separating the analysis infrastructure to its own file can land now, if you want to make a PR with just that commit.

The `consider_edge` function would be used to filter edges from the IR graph that don't matter for this analysis, and would be called when constructing the reversed graph for dependencies. Did you take a look at its use in the `UsedTemplateParams` analysis? That should hopefully help clear things up.

Easiest way for me to provide feedback on the `CanDeriveDebugAnalysis` would be to open a PR so I can leave comments inline easily.

**Comment by KiChjang** [comment]
FTR, `@highfive assign me` doesn't actually do anything facy behind the scenes, all it does is add a C-assigned tag to the issue, so if you do want to "assign" an issue to someone else, you can simply put the C-assigned tag on the issue.

**Comment by fitzgen** [comment]
> FTR, @highfive assign me doesn't actually do anything facy behind the scenes, all it does is add a C-assigned tag to the issue, so if you do want to "assign" an issue to someone else, you can simply put the C-assigned tag on the issue manually.

Huh. It seems the "assigned" field is pretty useless then...
