### ISSUE TITLE
Running test modifies files?

### ISSUE THREAD

**Issue by SirVer** [servo/rust-bindgen#788]
Running `cargo test --features testing_only_libclang_3_8` on a fresh checkout modifies the following files on my system:

~~~
$ git status
...
	modified:   tests/expectations/tests/libclang-3.8/auto.rs
	modified:   tests/expectations/tests/libclang-3.8/const_bool.rs
	modified:   tests/expectations/tests/libclang-3.8/constant-evaluate.rs
	modified:   tests/expectations/tests/libclang-3.8/partial-specialization-and-inheritance.rs
...
~~~

The tests all pass. System is Mac OS X, with llvm38 installed from homebrew.

Is this WAI?

**Comment by emilio** [comment]
Hi, thanks for the report!

Can you paste the diff? Ideally the tests shouldn't change (CI tests this, but it's Linux-only though).

**Comment by SirVer** [comment]
The diff is in [this gist](https://gist.github.com/SirVer/bfafd1b9fcfe4a48f22be1bfca203de4).

**Comment by emilio** [comment]
Huh, interesting, so that's definitely using the `clang_EvaluateExpression` API, which _should_ be 3.9+. Perhaps it was backported? Are you sure that you're using 3.8? What does `RUST_LOG=bindgen ./target/debug/bindgen <any-test>` say for the clang version

**Comment by SirVer** [comment]
I ran 

~~~
RUST_LOG=bindgen ./target/debug/bindgen tests/headers/whitelist_fix.hpp > output.log 2>&1
~~~

Which gave as the first 2 lines this information.

~~~
INFO:bindgen: Clang Version: Apple LLVM version 8.0.0 (clang-800.0.42.1)
WARN:bindgen: Couldn't parse libclang version
~~~

Full output in this [gist](https://gist.github.com/SirVer/eb665d3529800228c554c83281f15b75).

It seems that bindgen picks up the system installed llvm that comes bundled with Apples dev-tools (which are a require install if you want to do any kind of development on Mac). As you can see they do not follow the llvm versioning. Can I force bindgen to use a different llvm installation?

**Comment by emilio** [comment]
You can set `LIBCLANG_PATH` and/or `CLANG_PATH`. We use the `clang-sys` crate to load libclang, so I think it should be referenced from its docs.

And that's indeed a weird libclang version! I don't own a mac so I don't know how to investigate it, but presumably you could run the 3.9 tests without a problem.

Thanks for the report again!

**Comment by SirVer** [comment]
Indeed `cargo test --features testing_only_libclang_3_9` runs through without modifying any files and the tests are green. Also running `LIBCLANG_PATH=/usr/local/opt/llvm38/lib/llvm-3.8/lib cargo test --features testing_only_libclang_3_8` reports the correct clang version:

~~~
INFO:bindgen: Clang Version: clang version 3.8.1 (tags/RELEASE_381/final)
~~~

and all tests are green without modifying files. So everything working as intended and this was a PEBKAC. Thanks!
