### ISSUE TITLE
Automatically detect libclang version when testing and use appropriate expectation files

### ISSUE THREAD

**Issue by fitzgen** [servo/rust-bindgen#794]
Right now, we rely on the `testing_only_libclang_X` features to choose the correct expectation file for tests that have different output across libclang versions.

If none of those features are passed, then we should make an attempt to parse the libclang version and use those expectations, if possible.

I always forget to pass the `testing_only_libclang_X` feature when invoking `cargo test` and I expect others do too, so this would be a nice papercut fix.

We have a `clang_version` function already, we just need to check it in the `compare_generated_header` function in `tests/test.rs`.

If someone wants to work on this as their first bindgen issue, I can help mentor :)

**Comment by tz70s** [comment]
@highfive: assign me
I'm interested in working on this issue!

**Comment by tz70s** [comment]
Hi @fitzgen !

Sorry, I should ask for your opinion on working this issue first. I have few questions about it after pulling requests.
1. The LLVM version 3.7 is using `libclang-3.8` now, should I also add the auto transfer to it?
2. Should we leave `testing_only_libclang_X` feature remain and create auto detect if it is not specified?
3. How about modify `libclang-4` to `libclang-4.0`? This may reduce the condition branches and being compatible while if `libclang-4.1` appeared.

thanks!

**Comment by fitzgen** [comment]
Fixed by #796
