### ISSUE TITLE
Tutorial is outdated

### ISSUE THREAD

**Issue by est31** [servo/rust-bindgen#803]
The tutorial doesn't point to the latest bindgen release on crates.io: https://github.com/servo/rust-bindgen/blob/master/book/src/tutorial-1.md

Also it would be nice if it could be regenerated and re-uploaded to https://servo.github.io/rust-bindgen because the current version still has `no_unstable_rust` (cc #757).

**Comment by fitzgen** [comment]
1. Yes we need to update the text of the tutorial.

2. It looks like our `deploy-book.sh` script hasn't been deploying the book...

**Comment by fitzgen** [comment]
Fixed by #805

**Comment by est31** [comment]
@fitzgen many thanks!
