### ISSUE TITLE
Error in building a binding for a subset of Linux kernel headers

### ISSUE THREAD

**Issue by HolmesSherlock** [servo/rust-bindgen#806]
I tried to [generate header](https://github.com/HolmesSherlock/kernel-wrapper) for a selected subset of Linux kernel headers . However, the attempt fail with the following set of errors.

------------------------------------------
Error while building Linux kernel bindings
------------------------------------------

STD_KERNEL_PATH='/lib/modules/4.2.0-41-generic/build' cargo build
   Compiling kernel-wrapper v0.1.0 (file:///local/mnt/workspace/dipanjan/kwrap)
error: failed to run custom build command for `kernel-wrapper v0.1.0 (file:///local/mnt/workspace/dipanjan/kwrap)`
process didn't exit successfully: `/local/mnt/workspace/dipanjan/kwrap/target/debug/build/kernel-wrapper-abf16a8eacafefd0/build-script-build` (exit code: 101)
--- stdout
/lib/modules/4.2.0-41-generic/build/include/linux/init.h:142:6: error: variable has incomplete type 'void', err: true
/lib/modules/4.2.0-41-generic/build/include/linux/init.h:142:12: error: expected ';' after top level declarator, err: true
/lib/modules/4.2.0-41-generic/build/include/linux/init.h:143:11: error: expected ';' after top level declarator, err: true
/lib/modules/4.2.0-41-generic/build/include/linux/init.h:281:6: error: variable has incomplete type 'void', err: true
/lib/modules/4.2.0-41-generic/build/include/linux/init.h:281:12: error: expected ';' after top level declarator, err: true
/lib/modules/4.2.0-41-generic/build/include/linux/init.h:282:6: error: variable has incomplete type 'void', err: true
/lib/modules/4.2.0-41-generic/build/include/linux/init.h:282:12: error: expected ';' after top level declarator, err: true
/lib/modules/4.2.0-41-generic/build/include/linux/linkage.h:7:10: fatal error: 'asm/linkage.h' file not found, err: true

--- stderr
/lib/modules/4.2.0-41-generic/build/include/linux/init.h:142:6: error: variable has incomplete type 'void'
/lib/modules/4.2.0-41-generic/build/include/linux/init.h:142:12: error: expected ';' after top level declarator
/lib/modules/4.2.0-41-generic/build/include/linux/init.h:143:11: error: expected ';' after top level declarator
/lib/modules/4.2.0-41-generic/build/include/linux/init.h:281:6: error: variable has incomplete type 'void'
/lib/modules/4.2.0-41-generic/build/include/linux/init.h:281:12: error: expected ';' after top level declarator
/lib/modules/4.2.0-41-generic/build/include/linux/init.h:282:6: error: variable has incomplete type 'void'
/lib/modules/4.2.0-41-generic/build/include/linux/init.h:282:12: error: expected ';' after top level declarator
/lib/modules/4.2.0-41-generic/build/include/linux/linkage.h:7:10: fatal error: 'asm/linkage.h' file not found
thread 'main' panicked at 'Unable to generate kernel bindings: ()', /checkout/src/libcore/result.rs:859
note: Run with `RUST_BACKTRACE=1` for a backtrace.

make: *** [all] Error 101

**Comment by fitzgen** [comment]
Is it still true that the Linux kernel only compiles with GCC? If so, I think we're out of luck, because bindgen relies on libclang. The error spew suggests to me that libclang thinks this is not valid C code.

**Comment by HolmesSherlock** [comment]
I solved the problem, still I don't understand how it got solved.I used this [kbuild.mk](https://github.com/HolmesSherlock/rust.ko/blob/master/kbuild.mk) which supplies `STD_CLANG_ARGS='${c_flags}'`. I don't understand how `c_flags` is getting populated by the build system.

**Comment by fitzgen** [comment]
Ok, I am closing this issue since it seems that there were just required arguments that were missing, and this isn't fundamentally bindgen's fault.

If I've misunderstood, we can reopen this issue.

Cheers!
