### ISSUE TITLE
Generate pub const for most of anonymous enums

### ISSUE THREAD

**Issue by upsuper** [servo/rust-bindgen#84]
Anonymous enums usually serve as a container of scoped constants without linkage. It is more useful to have a `pub const` for each of its members, rather than an enum with some unique name.

Discussed this with @Manishearth on IRC, and he prefers having enum because that fits matching better. However, in majority of cases, you cannot get a variable with its type being an anonymous enum, which means you need a manual conversion anyway. And that manual conversion requires the knowledge of the name of the enum in binding, which is volatile.

There is one case, though, you can get a variable with an anonymous enum type, that someone writes `enum { XXX } var`, in which case @Manishearth's argument makes lots of sense. So I suggest that for all other cases, we generate `pub const`s rather than enums.

**Comment by emilio** [comment]
We do this for top-level anonymous enums IIRC (see the `NODE_` flags in stylo. I agree it makes sense to expand this behavior and shouldn't be too hard.

**Comment by upsuper** [comment]
I guess it is not hard to generate consts, but it might be hard to determine whether an anonymous enum is used like `enum { XXX } var;`. If that's the case, we can probably generate both enums and consts.

**Comment by upsuper** [comment]
FWIW, I want this because in servo/servo#13674, we use a static const from Gecko side, which leads to linking failure on Windows. And I want to either convert that static const to a macro or an enum constant. It seems to me the latter is better because it is scoped.

If we can have this enhancement implemented soonish, I would use enum constants for that, otherwise, I'll change it to a macro.
