### ISSUE TITLE
Re-introduce docopt?

### ISSUE THREAD

**Issue by emilio** [servo/rust-bindgen#87]
Seems like the performance issues docopt had (#46, https://github.com/docopt/docopt.rs/issues/195) are fixed.

Should we restore it?

**Comment by Yamakaky** [comment]
An alternative would be to use clap, which ia also very cool.

**Comment by fitzgen** [comment]
I like docopt because it forces us to at least minimally document our command line flags. That is a great property to have.

**Comment by Yamakaky** [comment]
I too love docopt for that. Clap does the reverse: it generates the `--help` from the options.

**Comment by fitzgen** [comment]
I was under the impression that calling `.help("...")` on `clap`'s builder was optional (meaning that the documentation is optional even if the help text contains all flags). Is that incorrect?

**Comment by Yamakaky** [comment]
If you don't set it, clap auto-generates the `--help`.

**Comment by jdub** [comment]
I'm going to send a quick PR to fix some inaccuracies in the current `--help`, but I can see it needs more love. If you have a preference either way for `docopt` / `clap`, I'd be happy to plug one in.

**Comment by Yamakaky** [comment]
The only thing I have against `clap` is that the matches are basically a `Map<String, String>`, while `docopt` auto-deserialize in a struct.

**Comment by jdub** [comment]
Looks like we'd be stuck with that style of interface either way for now, as `docopt` depends on a compiler plugin to deserialise into a struct, doesn't yet support custom derive, and I suspect Macros 1.1 might not land as soon as we'd hoped anyway.

I'll get started with `docopt`.

**Comment by jdub** [comment]
This can be resolved, as I reintroduced docopt… and then switched to clap in #228. 😂

**Comment by emilio** [comment]
Right, thanks!
